force-app/main/default/objects/Account/fields/Beta__c.field-meta.xml
<CustomField>
    <fullName>Beta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si es un candidato con el que no se quiere contactar</description>
    <inlineHelpText>Solo se cumplimentará desde Dirección Comercial</inlineHelpText>
    <label>Beta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MysteryClient__c.field-meta.xml
<CustomField>
    <fullName>MysteryClient__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si es un cliente de la competencia que ha llamado para hacer un estudio de mercado</description>
    <inlineHelpText>Solo se cumplimentará desde Dirección Comercial</inlineHelpText>
    <label>Mystery Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/PotencialResidente.recordType-meta.xml
<RecordType>
    <fullName>PotencialResidente</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo residente</description>
    <label>Potencial/Residente</label>
</RecordType>

force-app/main/default/classes/CuentasBetaMysteryClient.cls
/**
@description
Clase de un solo uso que actualiza todas las cuentas de familiar Allegado  e indican su centro actual.

Ejecucción: Database.executeBatch(new CuentasResidencia(), 200); En la consola anónima.

DATE 		AUTHOR 		DESCRIPTION
21/02/2023	LCS - MSA	Creation
23/02/2023	LCS - MSA	Ultima cuenta que no se actualizaba. Ahora si.

@author Leadclic Solutions
@date 21/02/2023
*/

global class CuentasBetaMysteryClient implements Schedulable,  Database.Batchable<sObject> {

    Id IdFamiliaAllegado = [SELECT Id FROM RecordType WHERE DeveloperName = 'FamiliaAllegado' Limit 1].Id;
    Id IdPotencialResidente = [SELECT Id FROM RecordType WHERE DeveloperName = 'PotencialResidente' Limit 1].Id;

    public Database.QueryLocator start(Database.BatchableContext bc) {
        string query = ('Select Id, Beta__c, MysteryClient__c FROM Account WHERE RecordTYPEId =: IdFamiliaAllegado');  
        return Database.getQueryLocator(query);
    }

    global void execute(SchedulableContext SC) {
        Database.executeBatch(new CuentasBetaMysteryClient(), 200); 
    }

    public void execute(Database.BatchableContext bc, List<Account> Cuentas){
        List<Account> Accounts2Update = new List<Account>();

        map<Id, Boolean> mIdCuenta_Beta = new map<Id, Boolean>();
        map<Id, Boolean> mIdCuenta_Mystery = new map<Id, Boolean>();

        //CUENTAS RESIDENTES, han de tener un contacto de tipo residente
        List<Contact> ListaContactos = [SELECT Id, Beta__c, MysteryClient__c, AccountId FROM Contact WHERE AccountId IN: Cuentas AND RecordTYPEId =: IdPotencialResidente];

        for (Contact contacto : ListaContactos) {
            mIdCuenta_Beta.put(contacto.AccountId, contacto.Beta__c);
            mIdCuenta_Mystery.put(contacto.AccountId, contacto.MysteryClient__c);
        }
        for(Account Cuenta : Cuentas){
            Cuenta.Beta__c = mIdCuenta_Beta.get(Cuenta.Id) == null? false : mIdCuenta_Beta.get(Cuenta.Id);
            Cuenta.MysteryClient__c = mIdCuenta_Mystery.get(Cuenta.Id) == null? false : mIdCuenta_Mystery.get(Cuenta.Id);
            Accounts2Update.add(Cuenta);
        }

        Database.SaveResult[] srList = Database.update(Accounts2Update, false);
        for (Database.SaveResult sr : srList) {
            if (!sr.isSuccess()) {
                // Operation failed, so get all errors                
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Account fields that affected this error: ' + err.getFields());
                }
            }
        }
    }
    public void finish(Database.BatchableContext bc){
    }
}