force-app/main/default/objects/Account/fields/Beta__c.field-meta.xml
<CustomField>
    <fullName>Beta__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si es un candidato con el que no se quiere contactar</description>
    <inlineHelpText>Solo se cumplimentará desde Dirección Comercial</inlineHelpText>
    <label>Beta</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MysteryClient__c.field-meta.xml
<CustomField>
    <fullName>MysteryClient__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Si es un cliente de la competencia que ha llamado para hacer un estudio de mercado</description>
    <inlineHelpText>Solo se cumplimentará desde Dirección Comercial</inlineHelpText>
    <label>Mystery Client</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/PotencialResidente.recordType-meta.xml
<RecordType>
    <fullName>PotencialResidente</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo residente</description>
    <label>Potencial/Residente</label>
</RecordType>

force-app/main/default/classes/CuentasBetaMysteryClientTest.cls
@isTest
public with sharing class CuentasBetaMysteryClientTest {
    @TestSetup
    static void setup(){
        List<Account> NuevasCuentas = new List<Account>();
        List<Contact> NuevosContactos = new List<Contact>();

        Id IdFamiliaAllegado = [SELECT Id FROM RecordType WHERE DeveloperName = 'FamiliaAllegado' Limit 1].Id;
        Id IdPotencialResidente = [SELECT Id FROM RecordType WHERE DeveloperName = 'PotencialResidente' Limit 1].Id;

        for(Integer i = 0; i<200;i++){
            Account Nueva = new Account();
            Nueva.Name = 'TestCuentaNueva' +i;
            Nueva.RecordTypeId = IdFamiliaAllegado;
            NuevasCuentas.add(Nueva);
        }

        insert NuevasCuentas;

        for(Integer i = 0; i<4;i++){
            Contact Nueva = new Contact();
            Nueva.LastName = 'Test';
            Nueva.FirstName = 'Test';

            //Generar False - False, True - False, False - True y True - True
            Nueva.Beta__c = (math.mod(i,2)>0)? False : True;
            Nueva.MysteryClient__c = (i>1)? False : True;
            Nueva.RecordTypeId = IdPotencialResidente;
			Nueva.AccountId = NuevasCuentas[i].Id;
            NuevosContactos.add(Nueva);
        }
        insert NuevosContactos;
    }
    @isTest 
    static void Test(){

        test.startTest();
        Database.executeBatch(new CuentasBetaMysteryClient(), 200); 
        test.stopTest();

        List<Account> ListaCuentasFalseFalse = [Select Id, Beta__c, MysteryClient__c FROM Account WHERE Beta__c = False AND MysteryClient__c = False];
        List<Account> ListaCuentasFalseTrue = [Select Id, Beta__c, MysteryClient__c FROM Account WHERE Beta__c = False AND MysteryClient__c = True];
        List<Account> ListaCuentasTrueFalse = [Select Id, Beta__c, MysteryClient__c FROM Account WHERE Beta__c = True AND MysteryClient__c = False];
        List<Account> ListaCuentasTrueTrue = [Select Id, Beta__c, MysteryClient__c FROM Account WHERE Beta__c = True AND MysteryClient__c = True];

        List<Contact> ListaContactosFalseFalse = [Select Id, AccountId FROM Contact WHERE Beta__c = False AND MysteryClient__c = False];
        List<Contact> ListaContactosFalseTrue = [Select Id, AccountId FROM Contact WHERE Beta__c = False AND MysteryClient__c = True];
        List<Contact> ListaContactosTrueFalse = [Select Id, AccountId FROM Contact WHERE Beta__c = True AND MysteryClient__c = False];
        List<Contact> ListaContactosTrueTrue = [Select Id, AccountId FROM Contact WHERE Beta__c = True AND MysteryClient__c = True];

        System.assert(ListaCuentasFalseFalse.size() == 197, 'El batch ha fallado'); //196 no asignados y 1 asignado
        System.assert(ListaCuentasFalseTrue.size() == 1, 'El batch ha fallado'); //1 Asignado
        System.assert(ListaCuentasTrueFalse.size() == 1, 'El batch ha fallado'); //1 Asignado
        System.assert(ListaCuentasTrueTrue.size() == 1, 'El batch ha fallado'); //1 Asignado

        System.assert(ListaContactosFalseTrue[0].AccountId == ListaCuentasFalseTrue[0].Id, 'El batch ha fallado');
        System.assert(ListaContactosTrueFalse[0].AccountId == ListaCuentasTrueFalse[0].Id, 'El batch ha fallado');
        System.assert(ListaContactosTrueTrue[0].AccountId == ListaCuentasTrueTrue[0].Id, 'El batch ha fallado');

    }
}