force-app/main/default/objects/Account/fields/CentroResidenciaActual__c.field-meta.xml
<CustomField>
    <fullName>CentroResidenciaActual__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo de tipo búsqueda para conocer el centro/residencia actual del contacto residente</description>
    <label>Centro/ Residencia Actual Residente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Centros/Residencias Actuales</relationshipLabel>
    <relationshipName>CentrosResidenciasActuales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodigoCentroSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoCentroSAP__c</fullName>
    <description>Identificador único del centro en SAP</description>
    <externalId>true</externalId>
    <label>Código del centro</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CentroResidencia.recordType-meta.xml
<RecordType>
    <fullName>CentroResidencia</fullName>
    <active>true</active>
    <description>Tipo de registro para residencias o centros</description>
    <label>Centro/Residencia</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/PotencialResidente.recordType-meta.xml
<RecordType>
    <fullName>PotencialResidente</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo residente</description>
    <label>Potencial/Residente</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/FechaSalida__c.field-meta.xml
<CustomField>
    <fullName>FechaSalida__c</fullName>
    <description>Fecha en la que el residente deja la plaza</description>
    <label>Fecha de salida</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plaza que ocupa el paciente en la residencia</description>
    <label>Plaza residencia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Residencia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ResidenciaIngreso__c</valueField>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Plaza residencia)</relationshipLabel>
    <relationshipName>Oportunidades7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RealSAP__c.field-meta.xml
<CustomField>
    <fullName>RealSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la oportunidad una vez se ha enviado a SAP está planificada o no.</description>
    <label>Real SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResidenciaIngreso__c.field-meta.xml
<CustomField>
    <fullName>ResidenciaIngreso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Centro al que ingresa el residente en esta oportunidad</description>
    <label>Residencia de ingreso</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroResidencia</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Residencia de Ingreso)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PlazaPrivada.recordType-meta.xml
<RecordType>
    <fullName>PlazaPrivada</fullName>
    <active>true</active>
    <businessProcess>Plaza privada</businessProcess>
    <description>Tipo de registro para el proceso de ventas de las plazas privadas</description>
    <label>Plaza privada</label>
</RecordType>

force-app/main/default/objects/Plaza__c/Plaza__c.object-meta.xml
<CustomObject>
    <description>En el objeto Plaza se recogerá toda la información de estructura, de módulos y de distribución de habitaciones y camas de los centros/ residencia así como de las plazas de Centro de día</description>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de Plaza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plaza__c/recordTypes/CentroDia.recordType-meta.xml
<RecordType>
    <fullName>CentroDia</fullName>
    <active>true</active>
    <description>Tipo de registro para las plazas de centro de día</description>
    <label>Centro de día</label>
</RecordType>

force-app/main/default/objects/Plaza__c/recordTypes/Residencia.recordType-meta.xml
<RecordType>
    <fullName>Residencia</fullName>
    <active>true</active>
    <description>Tipo de registro para las plazas de residencia</description>
    <label>Residencia</label>
</RecordType>

force-app/main/default/classes/TestCuentasResidencia.cls
/**
@description
Clase test de CuentasResidencia

DATE 		AUTHOR 		DESCRIPTION
21/02/2023	LCS - MSA	Creation
23/02/2023	LCS - MSA	Ultima cuenta que no se actualizaba. Ahora si.
22/05/2023  LCS - MSA	Corrección por el nuevo estado de las oportunidades.
16/01/2024  LCS - MSA	Corrección por la capacidad de clonar oportunidades.

@author Leadclic Solutions
@date 21/02/2023
*/

@isTest 
public class TestCuentasResidencia {

        private static final Id accountCentroRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CentroResidencia').getRecordTypeId();
        private static final Id plazaResidenciaRTId = Schema.SObjectType.Plaza__c.getRecordTypeInfosByDeveloperName().get('Residencia').getRecordTypeId();
        private static final Id plazaCentroDiaRTId = Schema.SObjectType.Plaza__c.getRecordTypeInfosByDeveloperName().get('CentroDia').getRecordTypeId();
        private static final Id accountFamiliaRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('FamiliaAllegado').getRecordTypeId();
        private static final Id contactFamiliarRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('FamiliaAllegado').getRecordTypeId();
        private static final Id contactResidenteRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('PotencialResidente').getRecordTypeId();
        private static final Id opportunityPlazaPrivadaRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('PlazaPrivada').getRecordTypeId();
        
    @TestSetup
    static void setup(){
        
        List<Account> NuevasCuentas = new List<Account>();
        List<Opportunity> NuevasOportunidades = new List<Opportunity>();
        List<Contact> NuevosContactos = new List<Contact>();
        List<ContentDocument> NuevosArchivos = new List<ContentDocument>();

        

    Account centro = new Account(
            Name = 'Centro de prueba',
            RecordTypeId = accountCentroRTId,
            CodigoCentroSAP__c = '2808'
        );
        insert centro;

        Account centro2 = new Account(
            Name = 'Centro de prueba2',
            RecordTypeId = accountCentroRTId,
            CodigoCentroSAP__c = '2809'
        );
        insert centro2;
        
        //Se crean 200 cuentas
        
        for(Integer i = 0; i<200;i++){
            Account Nueva = new Account();
            Nueva.Name = 'TestCuentaNueva' +i;
            NuevasCuentas.add(Nueva);
            Nueva.RecordTypeId = accountFamiliaRTId;
        }
        insert NuevasCuentas;
        
        //Se crean 400 oportunidades
        
        for(Integer i = 0; i<400;i++){
            Opportunity Nueva = new Opportunity();
            Nueva.Name = 'TestOportunidadNueva';
            if(i > 199){
            Nueva.AccountId = NuevasCuentas[i-200].Id;
            } else {
            Nueva.AccountId = NuevasCuentas[i].Id;
            }
            NuevasOportunidades.add(Nueva);
            Nueva.StageName = 'Cerrada - Éxito';
            Nueva.RealSAP__c = true;
            Nueva.FechaSalida__c = System.today() +i;
            Nueva.CloseDate = System.today();
            if(i>199){
                Nueva.ResidenciaIngreso__c = centro.Id;
            } else{
                Nueva.ResidenciaIngreso__c = centro2.Id;
            }
            
        }
        insert NuevasOportunidades;
        for(Integer i = 0; i<400;i++){
            NuevasOportunidades[i].FechaSalida__c = System.today() +i;
        }
        update NuevasOportunidades;
    }
        @isTest 
        static void rellenaCentro(){
            test.startTest();
            Database.executeBatch(new CuentasResidencia(), 200); 
            test.stopTest();
            List<Account> centro = [SELECT Id from Account where CodigoCentroSAP__c = '2808'];
            List<Account> cuentas = [SELECT Id FROM Account WHERE CentroResidenciaActual__c =: centro];
            System.assertEquals(cuentas.size(), 200);
        }
    
}