force-app/main/default/objects/Account/fields/CodigoCentroSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoCentroSAP__c</fullName>
    <description>Identificador único del centro en SAP</description>
    <externalId>true</externalId>
    <label>Código del centro</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mensaje_Error__mdt/Mensaje_Error__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata Type con los valores de errorCode y errorDescription para los servicios REST de Amavir.</description>
    <label>Mensaje Error</label>
    <pluralLabel>Mensajes Error</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mensaje_Error__mdt/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <description>Código de error para respuesta servicios REST</description>
    <label>Error Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de la oportunidad. Viene con el valor de espisodio en SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plaza que ocupa el paciente en la residencia</description>
    <label>Plaza residencia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Residencia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ResidenciaIngreso__c</valueField>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Plaza residencia)</relationshipLabel>
    <relationshipName>Oportunidades7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaDomingo__c.field-meta.xml
<CustomField>
    <fullName>PlazaDomingo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Domingo en el centro de día ha de rellenarse este campo</description>
    <label>Domingo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Domingo</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Domingo)</relationshipLabel>
    <relationshipName>Oportunidades6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaJueves__c.field-meta.xml
<CustomField>
    <fullName>PlazaJueves__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Jueves en el centro de día ha de rellenarse este campo</description>
    <label>Jueves</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Jueves</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Jueves)</relationshipLabel>
    <relationshipName>Oportunidades3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaLunes__c.field-meta.xml
<CustomField>
    <fullName>PlazaLunes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Lunes en el centro de día ha de rellenarse este campo</description>
    <label>Lunes</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Lunes</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Lunes)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaMartes__c.field-meta.xml
<CustomField>
    <fullName>PlazaMartes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Martes en el centro de día ha de rellenarse este campo</description>
    <label>Martes</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Martes</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Martes)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaMiercoles__c.field-meta.xml
<CustomField>
    <fullName>PlazaMiercoles__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Miercoles en el centro de día ha de rellenarse este campo</description>
    <label>Miércoles</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Miércoles</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Miércoles)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaSabado__c.field-meta.xml
<CustomField>
    <fullName>PlazaSabado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Sábado en el centro de día ha de rellenarse este campo</description>
    <label>Sábado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Sábado</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Sábado)</relationshipLabel>
    <relationshipName>Oportunidades5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaViernes__c.field-meta.xml
<CustomField>
    <fullName>PlazaViernes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Viernes en el centro de día ha de rellenarse este campo</description>
    <label>Viernes</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Viernes</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Viernes)</relationshipLabel>
    <relationshipName>Oportunidades4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResidenciaIngreso__c.field-meta.xml
<CustomField>
    <fullName>ResidenciaIngreso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Centro al que ingresa el residente en esta oportunidad</description>
    <label>Residencia de ingreso</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroResidencia</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Residencia de Ingreso)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plaza__c/Plaza__c.object-meta.xml
<CustomObject>
    <description>En el objeto Plaza se recogerá toda la información de estructura, de módulos y de distribución de habitaciones y camas de los centros/ residencia así como de las plazas de Centro de día</description>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de Plaza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plaza__c/fields/Cama__c.field-meta.xml
<CustomField>
    <fullName>Cama__c</fullName>
    <description>Código de la cama</description>
    <label>Cama</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plaza__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <description>Centro al que pertenece la plaza</description>
    <label>Centro</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plazas</relationshipLabel>
    <relationshipName>Plazas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plaza__c/fields/PlazaOcupada__c.field-meta.xml
<CustomField>
    <fullName>PlazaOcupada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la plaza está en uso actualmente en alguna oportunidad en estado cerrada o reserva de plaza</description>
    <label>Plaza ocupada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plaza__c/recordTypes/Residencia.recordType-meta.xml
<RecordType>
    <fullName>Residencia</fullName>
    <active>true</active>
    <description>Tipo de registro para las plazas de residencia</description>
    <label>Residencia</label>
</RecordType>

force-app/main/default/objects/RegistrosDeErrores__c/RegistrosDeErrores__c.object-meta.xml
<CustomObject>
    <description>Este objeto es un registro de errores ocasionado por los Web Services donde se verá la clase donde se ha generado el error, el mensaje que hemos recibido y el código de error.</description>
    <label>Registro de Error</label>
    <nameField>
        <displayFormat>Error-{0000000}</displayFormat>
        <label>Nombre de Registros de Errores</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de Errores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegistrosDeErrores__c/fields/ClaseGeneradora__c.field-meta.xml
<CustomField>
    <fullName>ClaseGeneradora__c</fullName>
    <description>Nos indica donde se ha ocasionado el error</description>
    <label>Clase Generadora</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/fields/CodigoError__c.field-meta.xml
<CustomField>
    <fullName>CodigoError__c</fullName>
    <description>Nos indica el código donde se ha ocasionado dicho error</description>
    <label>Código de Error</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/fields/DescripcionError__c.field-meta.xml
<CustomField>
    <fullName>DescripcionError__c</fullName>
    <description>Nos dice cual es la descripción del error generado.</description>
    <label>Descripción del Error</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/fields/MensajeRecibido__c.field-meta.xml
<CustomField>
    <fullName>MensajeRecibido__c</fullName>
    <description>Nos indica que el mensaje  que hemos recibido para que se ocasione el error.</description>
    <label>Mensaje Recibido</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/WSReajustarOcupacion.cls
/** 
@description
<pre>
Servicio web RESTful que actualizará la ocupación mediante un Batch Apex</br>

FECHA       AUTOR   	    DESCRIPCION<br/>
16/01/2024	MSA - LCS       Creado
</pre>
@author Leadclic Solutions
@date 7/11/2023
*/
@RestResource(urlMapping='/WSReajustarOcupacion/*')
global with sharing class WSReajustarOcupacion implements Schedulable,  Database.Batchable<sObject>{

    private PayloadIn payload_global;
    private Set<String> Episodios;

    public WSReajustarOcupacion(PayloadIn payload) {
        payload_global = payload;
        Episodios = payload.Episodios.keySet();
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {

        Account Centro = [SELECT Id FROM Account WHERE CodigoCentroSAP__c =: payload_global.Centro limit 1];
        List<Plaza__c> ListaPlazas = [SELECT Name, Id, Cama__c, PlazaOcupada__c FROM Plaza__c WHERE Cuenta__c =: Centro.Id];

        map<String, Id> mCamaId = new map<String, Id>();

        for(Plaza__c plaza : ListaPlazas){
            plaza.PlazaOcupada__c = false;
            mCamaId.put(plaza.Cama__c, plaza.Id);
        }
        update ListaPlazas;
                     
        string query = 'SELECT Id, IdExternoSAP__c, Plaza__c, PlazaLunes__c, PlazaMartes__c, PlazaMiercoles__c, PlazaJueves__c, PlazaViernes__c, PlazaSabado__c, PlazaDomingo__c FROM Opportunity WHERE IdExternoSAP__c =: Episodios AND ResidenciaIngreso__r.Name != null';  
        return Database.getQueryLocator(query);
    }

    global void execute(SchedulableContext SC) {
        Database.executeBatch(new CuentasResidencia(), 200); 
    }

    public void execute(Database.BatchableContext bc, List<Opportunity> ListaOportunidades){
        List<Id> ListaPlazasOcupadas = new List<Id>();
        List<Plaza__c> ListaPlazasOcupadasUpdate = new List<Plaza__c>();

        Account Centro = [SELECT Id FROM Account WHERE CodigoCentroSAP__c =: payload_global.Centro];
        List<Plaza__c> ListaPlazas = [SELECT Name, Id, Cama__c, PlazaOcupada__c FROM Plaza__c WHERE Cuenta__c =: Centro.Id];

        map<String, Id> mCamaId = new map<String, Id>();

        for(Plaza__c plaza : ListaPlazas){
            plaza.PlazaOcupada__c = false;
            mCamaId.put(plaza.Cama__c, plaza.Id);
        }

        for(Opportunity Oportunidad : ListaOportunidades){
            Oportunidad.Plaza__c = mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Residencia'));
            Oportunidad.PlazaLunes__c = mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Lunes') + 'L');
            Oportunidad.PlazaMartes__c = mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Martes') + 'M');
            Oportunidad.PlazaMiercoles__c = mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Miercoles') + 'X');
            Oportunidad.PlazaJueves__c = mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Jueves') + 'J');
            Oportunidad.PlazaViernes__c = mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Viernes') + 'V');
            Oportunidad.PlazaSabado__c = mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Sabado') + 'S');
            Oportunidad.PlazaDomingo__c = mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Domingo') + 'D');

            ListaPlazasOcupadas.add(mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Residencia')));
            ListaPlazasOcupadas.add(mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Lunes') + 'L'));
            ListaPlazasOcupadas.add(mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Martes') + 'M'));
            ListaPlazasOcupadas.add(mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Miercoles') + 'X'));
            ListaPlazasOcupadas.add(mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Jueves') + 'J'));
            ListaPlazasOcupadas.add(mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Viernes') + 'V'));
            ListaPlazasOcupadas.add(mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Sabado') + 'S'));
            ListaPlazasOcupadas.add(mCamaId.get(payload_global.Episodios.get(Oportunidad.IdExternoSAP__c).get('Domingo') + 'D'));
        }

        ListaPlazasOcupadasUpdate = [SELECT Id, PlazaOcupada__c FROM Plaza__c WHERE Id IN: ListaPlazasOcupadas];

        for(Plaza__c plaza : ListaPlazasOcupadasUpdate){
            plaza.PlazaOcupada__c = true;
        }
        update ListaOportunidades;
        update ListaPlazasOcupadasUpdate;
    }
    public void finish(Database.BatchableContext bc){

        System.debug(payload_global);
        System.debug(Episodios);

    }

    ///////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////

    //Web Service

    ///////////////////////////////////////////////////////////
    ///////////////////////////////////////////////////////////
    @HttpPost
    global static PayloadOut WSReajustarOcupacion(PayloadIn payload) {

        PayloadOut payloadOut = new PayloadOut();

        try{
            payloadOut.errorCode = '-1';
            payloadOut.errorDescription = 'Se va a proceder a realizar la ocupación';
            Database.executeBatch(new WSReajustarOcupacion(payload), 20);

        }catch(Exception e){
            Mensaje_Error__mdt resp = fetchResponses('err500');
            payloadOut.errorCode = resp.Error_Code__c;
            payloadOut.errorDescription = e.getMessage();
            CreateErrorLog(resp.Error_Code__c, e.getMessage(), payload);
        }

        return payloadOut;
    }

    //Wrapper class de entrada
    global class PayloadIn {
        public String Centro {get;set;}
        public map<String, map<String, String>> Episodios {get;set;}
    }

    //Wrapper class de salida
    global class PayloadOut {
        public String errorDescription {get;set;}
        public String errorCode {get;set;}
    }

    /**
	@description	Método para recuperar los códigos y mensajes de respuesta
	@param 			String errReference nombre del Custom Metadata Type que se quiere recuperar
	@return			Mensaje_Error__mdt con los campos de la respuesta
	*/ 

    public static Mensaje_Error__mdt fetchResponses(String errReference){
        Mensaje_Error__mdt response = Mensaje_Error__mdt.getInstance(errReference);
        Return response;
    }

    /**
	@description	Método para generar errores una vez se haya dado un error
	@param 			String code codigo de error
    @param 			String ErrorDescription descripcion del error
    @param 			PayloadIn Payload datos de entrada
	@return			Mensaje_Error__mdt con los campos de la respuesta
	*/ 

    public static void CreateErrorLog(String Code, String ErrorDescription, PayloadIn Payload){
        RegistrosDeErrores__c ErrorGenerado = new RegistrosDeErrores__c();
        
        ErrorGenerado.CodigoError__c = Code;
        ErrorGenerado.DescripcionError__c = ErrorDescription;
        ErrorGenerado.MensajeRecibido__c = JSON.serialize(Payload);
        ErrorGenerado.ClaseGeneradora__c = 'WSGestionUsuarios';

        insert ErrorGenerado;
    }
}