force-app/main/default/objects/Account/fields/CodigoCentroSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoCentroSAP__c</fullName>
    <description>Identificador único del centro en SAP</description>
    <externalId>true</externalId>
    <label>Código del centro</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CentroResidencia.recordType-meta.xml
<RecordType>
    <fullName>CentroResidencia</fullName>
    <active>true</active>
    <description>Tipo de registro para residencias o centros</description>
    <label>Centro/Residencia</label>
</RecordType>

force-app/main/default/objects/Contact/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP para los residentes</description>
    <externalId>true</externalId>
    <label>Identificador de SAP Residentes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PotencialResidente.recordType-meta.xml
<RecordType>
    <fullName>PotencialResidente</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo residente</description>
    <label>Potencial/Residente</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DetalleMotivoIngreso__c.field-meta.xml
<CustomField>
    <fullName>DetalleMotivoIngreso__c</fullName>
    <description>Campo de tipo lista de selección para conocer el detalle motivo de ingreso</description>
    <label>Detalle Motivo de Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MotivoIngreso__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>DetalleMotivoIngreso</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaIngreso__c.field-meta.xml
<CustomField>
    <fullName>FechaIngreso__c</fullName>
    <description>FechaIngreso</description>
    <label>Fecha de ingreso</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de la oportunidad. Viene con el valor de espisodio en SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MotivoIngreso__c.field-meta.xml
<CustomField>
    <fullName>MotivoIngreso__c</fullName>
    <description>Campo de tipo lista de selección para conocer el motivo de ingreso</description>
    <label>Motivo de Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MotivoIngreso</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plaza que ocupa el paciente en la residencia</description>
    <label>Plaza residencia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Residencia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ResidenciaIngreso__c</valueField>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Plaza residencia)</relationshipLabel>
    <relationshipName>Oportunidades7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RealSAP__c.field-meta.xml
<CustomField>
    <fullName>RealSAP__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la oportunidad una vez se ha enviado a SAP está planificada o no.</description>
    <label>Real SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResidenciaIngreso__c.field-meta.xml
<CustomField>
    <fullName>ResidenciaIngreso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Centro al que ingresa el residente en esta oportunidad</description>
    <label>Residencia de ingreso</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroResidencia</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Residencia de Ingreso)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResidenciaPreferencia__c.field-meta.xml
<CustomField>
    <fullName>ResidenciaPreferencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Residencia de preferencia elegida por el candidato</description>
    <label>Residencia de preferencia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroResidencia</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Residencia de preferencia)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoPlaza__c.field-meta.xml
<CustomField>
    <fullName>TipoPlaza__c</fullName>
    <description>Tipo de plaza que se está negociando</description>
    <label>Tipo de plaza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoPlaza</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Traslado.recordType-meta.xml
<RecordType>
    <fullName>Traslado</fullName>
    <active>true</active>
    <businessProcess>Traslado</businessProcess>
    <description>Tipo de registro para el proceso de ventas de los traslados</description>
    <label>Traslado</label>
</RecordType>

force-app/main/default/objects/Plaza__c/Plaza__c.object-meta.xml
<CustomObject>
    <description>En el objeto Plaza se recogerá toda la información de estructura, de módulos y de distribución de habitaciones y camas de los centros/ residencia así como de las plazas de Centro de día</description>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de Plaza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plaza__c/fields/Cama__c.field-meta.xml
<CustomField>
    <fullName>Cama__c</fullName>
    <description>Código de la cama</description>
    <label>Cama</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plaza__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <description>Centro al que pertenece la plaza</description>
    <label>Centro</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plazas</relationshipLabel>
    <relationshipName>Plazas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plaza__c/fields/DiaSemana__c.field-meta.xml
<CustomField>
    <fullName>DiaSemana__c</fullName>
    <description>Día de la semana</description>
    <label>Día de la semana</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lunes</fullName>
            </value>
            <value>
                <fullName>Martes</fullName>
            </value>
            <value>
                <fullName>Miércoles</fullName>
            </value>
            <value>
                <fullName>Jueves</fullName>
            </value>
            <value>
                <fullName>Viernes</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plaza__c/fields/PlazaOcupada__c.field-meta.xml
<CustomField>
    <fullName>PlazaOcupada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica si la plaza está en uso actualmente en alguna oportunidad en estado cerrada o reserva de plaza</description>
    <label>Plaza ocupada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plaza__c/fields/TipoPlaza__c.field-meta.xml
<CustomField>
    <fullName>TipoPlaza__c</fullName>
    <description>Indica si la plaza está ocupada por una plaza pública o privada. Solo se rellena en las plazas ocupadas, las libres no tienen esta caracteristica.</description>
    <label>Tipo de plaza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoPlaza</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plaza__c/recordTypes/CentroDia.recordType-meta.xml
<RecordType>
    <fullName>CentroDia</fullName>
    <active>true</active>
    <description>Tipo de registro para las plazas de centro de día</description>
    <label>Centro de día</label>
</RecordType>

force-app/main/default/objects/Plaza__c/recordTypes/Residencia.recordType-meta.xml
<RecordType>
    <fullName>Residencia</fullName>
    <active>true</active>
    <description>Tipo de registro para las plazas de residencia</description>
    <label>Residencia</label>
</RecordType>

force-app/main/default/globalValueSets/DetalleMotivoIngreso.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Autolisis</fullName>
    </customValue>
    <customValue>
        <fullName>Bipolar</fullName>
    </customValue>
    <customValue>
        <fullName>Depresión / Ansiedad</fullName>
    </customValue>
    <customValue>
        <fullName>Enfermedad neurológica</fullName>
    </customValue>
    <customValue>
        <fullName>Esquizofrenia</fullName>
    </customValue>
    <customValue>
        <fullName>TOC</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>ACV / Ictus</fullName>
    </customValue>
    <customValue>
        <fullName>Amputación</fullName>
    </customValue>
    <customValue>
        <fullName>Caídas</fullName>
    </customValue>
    <customValue>
        <fullName>Cáncer</fullName>
    </customValue>
    <customValue>
        <fullName>Esclerosis</fullName>
    </customValue>
    <customValue>
        <fullName>Fractura</fullName>
    </customValue>
    <customValue>
        <fullName>Problemas cardiovasculares (Infarto, ICC, HTA, Arritmias, Fibrilación, Diabetes…)</fullName>
    </customValue>
    <customValue>
        <fullName>Movilidad reducida</fullName>
    </customValue>
    <customValue>
        <fullName>Paliativos</fullName>
    </customValue>
    <customValue>
        <fullName>Parkinson</fullName>
    </customValue>
    <customValue>
        <fullName>Operación / Convalecencia</fullName>
    </customValue>
    <customValue>
        <fullName>Problemas respiratorios (O2, Neutomonía, EPOC...)</fullName>
    </customValue>
    <customValue>
        <fullName>Otras</fullName>
    </customValue>
    <customValue>
        <fullName>Alteraciones de conducta</fullName>
    </customValue>
    <customValue>
        <fullName>Alzheimer</fullName>
    </customValue>
    <customValue>
        <fullName>Cuerpo Lewy</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia fronto-temporal</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia senil</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia vascular</fullName>
    </customValue>
    <customValue>
        <fullName>Desorientación / Riesgo fuga</fullName>
    </customValue>
    <customValue>
        <fullName>Perdidas memoria</fullName>
    </customValue>
    <customValue>
        <fullName>ELA</fullName>
    </customValue>
    <customValue>
        <fullName>De la competencia por descontento</fullName>
    </customValue>
    <description>Valores del campo Detalle Motivo de Ingreso del Lead y Opp</description>
    <masterLabel>Detalle Motivo de Ingreso</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MotivoIngreso.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Psicogeriatría</fullName>
    </customValue>
    <customValue>
        <fullName>Dependencia cognitiva</fullName>
    </customValue>
    <customValue>
        <fullName>Dependencia física</fullName>
    </customValue>
    <customValue>
        <fullName>Dependencia física y cognitiva</fullName>
    </customValue>
    <customValue>
        <fullName>Aspectos sociales</fullName>
    </customValue>
    <customValue>
        <fullName>Traslado residencia</fullName>
    </customValue>
    <customValue>
        <fullName>Plaza Pública</fullName>
    </customValue>
    <description>Valores de motivo de ingreso en Leads y Opps</description>
    <masterLabel>Motivo de Ingreso</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TipoPlaza.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P</fullName>
        <label>Privada</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Pública</label>
    </customValue>
    <description>Tipo de plaza que se solicita</description>
    <masterLabel>Tipo de plaza</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestWSReajustarOcupacion.cls
/**
@description
Clase test de WSReajustarOcupacion

DATE 		AUTHOR 		DESCRIPTION
16/01/2024  LCS - MSA	Creación.
14/06/2024  LCS - MSA   Corrección por cambio en VR.

@author Leadclic Solutions
@date 16/01/2024
*/

@isTest
public with sharing class TestWSReajustarOcupacion {
    
    @testSetup 
    static void setup() {

        Profile p = [SELECT Id FROM Profile WHERE Name='Administrador del sistema'];
        User u2 = new User(Alias = 'uinte', Email='newuser@testorg.com',
        EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
        LocaleSidKey='en_US', ProfileId = p.Id,
        TimeZoneSidKey='America/Los_Angeles', UserName='newuser@testorg.com');

        //Insertamos Cuenta de Residente en residencia
        List<Account> lAccount2Ins = new List<Account>();
        Account acctResidente = new Account(Name='CuentaResidentePrueba');
        lAccount2Ins.add(acctResidente);

        //Insertamos Cuenta de Residente en Centro de día 
        Account acctResidenteCD = new Account(Name='CuentaResidentePruebaCD');
        lAccount2Ins.add(acctResidenteCD);

        // Insertamos una residencia
        RecordType rtCentroResidenciaId = [SELECT Id FROM RecordType WHERE DeveloperName ='CentroResidencia' and SobjectType = 'Account'];
        RecordType rtOppTraslado = [SELECT Id FROM RecordType WHERE DeveloperName ='Traslado' and SobjectType = 'Opportunity'];
        Account acctResidencia = new Account(Name='CuentaResidenciaPrueba', RecordTypeId=rtCentroResidenciaId.Id, CodigoCentroSAP__c = '0201');
        lAccount2Ins.add(acctResidencia);

        insert lAccount2Ins;


        //Insertamos el contacto
        RecordType rtid = [SELECT Id FROM RecordType WHERE DeveloperName ='PotencialResidente' and SobjectType = 'Contact'];

        //Recogemos RT de Plaza
        RecordType rtPlazaResidencia = [SELECT Id FROM RecordType WHERE DeveloperName ='Residencia' and SobjectType = 'Plaza__c'];
        RecordType rtPlaza = [SELECT Id FROM RecordType WHERE DeveloperName ='CentroDia' and SobjectType = 'Plaza__c'];
        
        Contact contactResidencia = new Contact (RecordTypeId=rtid.Id,
                                        IdExternoSAP__c='88888888',
                                        AccountId=acctResidente.Id,
                                        FirstName='ResidentePrueba',
                                        LastName='ApellidoPrueba',
                                        MailingStreet='Ancha',
                                        MailingPostalCode='28005',
                                        MailingCity='Madrid',
                                        MobilePhone='945588032',
                                        Phone='916983265',
                                        Email='testmail@test.com');
        insert contactResidencia;

        Contact contactCD = new Contact (RecordTypeId=rtid.Id,
                                        IdExternoSAP__c='999999999',
                                        AccountId=acctResidenteCD.Id,
                                        FirstName='ResidentePrueba2',
                                        LastName='ApellidoPrueba2',
                                        MailingStreet='Ancha2',
                                        MailingPostalCode='28005',
                                        MailingCity='Madrid',
                                        MobilePhone='687654321',
                                        Phone='945786123',
                                        Email='testmail2@test.com');
        insert contactCD;

        // Lista para insertar las plazas
        List<Plaza__c> lPlazas = new List<Plaza__c> ();
        //Insertamos plaza origen residencia
        Plaza__c plazaResidenciaOrigen = new Plaza__c(
            Cuenta__c=acctResidencia.Id,
            Cama__C='0201001A',
            TipoPlaza__c='P',
            PlazaOcupada__c=true,
            RecordTypeId = rtPlazaResidencia.Id
        );
        lPlazas.add(plazaResidenciaOrigen);
        //Insertamos plaza destino residencia
        Plaza__c plazaResidenciaDestino = new Plaza__c(
            Cama__c='0201019A',
            PlazaOcupada__c=false,
            Cuenta__c=acctResidencia.Id,
            TipoPlaza__c='P',
            RecordTypeId = rtPlazaResidencia.Id
        );
        lPlazas.add(plazaResidenciaDestino);
        //Insertamos plazas de centros de día
        Plaza__c plazaLunes = new Plaza__c(
            Cuenta__c=acctResidencia.Id,
            Cama__c='01CDP011L',
            TipoPlaza__c='P',
            PlazaOcupada__c=true,
            RecordTypeId = rtPlaza.Id,
            DiaSemana__c = 'Lunes'
        );
        lPlazas.add(plazaLunes);
        Plaza__c plazaMartes = new Plaza__c(
            Cuenta__c=acctResidencia.Id,
            Cama__c='01CDP011M',
            TipoPlaza__c='P',
            PlazaOcupada__c=false,
            RecordTypeId = rtPlaza.Id,
            DiaSemana__c = 'Martes'
        );
        lPlazas.add(plazaMartes);
        Plaza__c plazaMiercoles = new Plaza__c(
            Cuenta__c=acctResidencia.Id,
            Cama__c='01CDP011X',
            TipoPlaza__c='P',
            PlazaOcupada__c=false,
            RecordTypeId = rtPlaza.Id,
            DiaSemana__c = 'Miércoles'
        );
        lPlazas.add(plazaMiercoles);
        Plaza__c plazaJueves = new Plaza__c(
            Cuenta__c=acctResidencia.Id,
            Cama__c='01CDP011J',
            TipoPlaza__c='P',
            PlazaOcupada__c=false,
            RecordTypeId = rtPlaza.Id,
            DiaSemana__c = 'Jueves'
        );
        lPlazas.add(plazaJueves);
        Plaza__c plazaViernes = new Plaza__c(
            Cuenta__c=acctResidencia.Id,
            Cama__c='01CDP011V',
            TipoPlaza__c='P',
            PlazaOcupada__c=false,
            RecordTypeId = rtPlaza.Id,
            DiaSemana__c = 'Viernes'
        );
        lPlazas.add(plazaViernes);
        Plaza__c plazaSabado = new Plaza__c(
            Cuenta__c=acctResidencia.Id,
            Cama__c='01CDP011S',
            TipoPlaza__c='P',
            PlazaOcupada__c=false,
            RecordTypeId = rtPlaza.Id,
            DiaSemana__c = 'Sábado'
        );
        lPlazas.add(plazaSabado);
        Plaza__c plazaDomingo = new Plaza__c(
            Cuenta__c=acctResidencia.Id,
            Cama__c='01CDP011D',
            TipoPlaza__c='P',
            PlazaOcupada__c=false,
            RecordTypeId = rtPlaza.Id,
            DiaSemana__c = 'Domingo'
        );
        lPlazas.add(plazaDomingo);
        // Otra plaza diferente para el Lunes
        Plaza__c plazaLunes2 = new Plaza__c(
            Cuenta__c=acctResidencia.Id,
            Cama__c='01CDP012L',
            TipoPlaza__c='P',
            PlazaOcupada__c=false,
            RecordTypeId = rtPlaza.Id,
            DiaSemana__c = 'Lunes'
        );
        lPlazas.add(plazaLunes2);
        insert lPlazas;

        //Insertamos Oportunidad con el IdResidente (IdExternoSAP__c) que se va a enviar en la prueba y la plaza original
        Opportunity opportunityResidencia = new Opportunity(
            Plaza__c=plazaResidenciaOrigen.Id,
            AccountId=acctResidente.Id,
            IdExternoSAP__c='88888888',
            Name='Baldomero Dominguez',
            StageName='Cerrada - Éxito',
            ResidenciaIngreso__c = acctResidencia.Id,
            CloseDate=date.parse('01/01/2018'),
            FechaIngreso__c = Date.today(),
            TipoPlaza__c = 'P',
            ResidenciaPreferencia__c = acctResidencia.Id,
            RealSAP__c = true,
            MotivoIngreso__c = 'Psicogeriatría',
            DetalleMotivoIngreso__c = 'Autolisis'
        );
        insert opportunityResidencia;
        opportunityResidencia.IdExternoSAP__c='88888888';
        update opportunityResidencia;

        //Insertamos Oportunidad con el IdResidente (IdExternoSAP__c) que se va a enviar en la prueba y la plaza original
        Opportunity opportunityCD = new Opportunity(
            AccountId=acctResidenteCD.Id,
            IdExternoSAP__c='999999999',
            Name='Baldomero Dominguez',
            StageName='Cerrada - Éxito',
            ResidenciaIngreso__c = acctResidencia.Id,
            CloseDate=date.parse('01/01/2018'),
            FechaIngreso__c = Date.today(),
            TipoPlaza__c = 'P',
            ResidenciaPreferencia__c = acctResidencia.Id,
            RealSAP__c = true,
            MotivoIngreso__c = 'Psicogeriatría',
            DetalleMotivoIngreso__c = 'Autolisis'
        );
        insert opportunityCD;
        opportunityCD.IdExternoSAP__c='999999999';
        update opportunityCD;
        
        OpportunityContactRole ocr1 = new OpportunityContactRole();
			
		ocr1.ContactId = contactCD.Id;
		ocr1.OpportunityId = opportunityCD.Id;
		ocr1.IsPrimary = FALSE;
		ocr1.Role = 'Residente';
		insert ocr1;     

    }

    /**
    @description    Método para lanzar la llamada
    @param          
    @return         
     */
    @isTest static void test() {

        Test.startTest();
            WSReajustarOcupacion.PayloadIn payload;
            payload = new WSReajustarOcupacion.PayloadIn();

            WSReajustarOcupacion.PayloadOut payloadOut;
            payloadOut = new WSReajustarOcupacion.PayloadOut();

            map<String, String> mPlazas = new map<String,String>();
            map<String, map<String, String>> mEpisodioPlazas = new map<String, map<String, String>>();

            mPlazas.put('Residencia','0201019A');
            mPlazas.put('Lunes','01CDP011M');
            mPlazas.put('Martes','');
            mPlazas.put('Miercoles','');
            mPlazas.put('Jueves','');
            mPlazas.put('Viernes','');
            mPlazas.put('Sabado','');
            mPlazas.put('Domingo','');

            mEpisodioPlazas.put('88888888', mPlazas);

            payload.Centro = '0201';
            payload.Episodios = mEpisodioPlazas;

            payloadOut = WSReajustarOcupacion.WSReajustarOcupacion(payload);
        Test.stopTest();
    }

}