force-app/main/default/objects/Account/fields/CodigoCentroSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoCentroSAP__c</fullName>
    <description>Identificador único del centro en SAP</description>
    <externalId>true</externalId>
    <label>Código del centro</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP para los residentes</description>
    <externalId>true</externalId>
    <label>Identificador de SAP Residentes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parentesco__c.field-meta.xml
<CustomField>
    <fullName>Parentesco__c</fullName>
    <description>Parentesco de la persona de contacto</description>
    <label>Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parentesco</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaSalida__c.field-meta.xml
<CustomField>
    <fullName>FechaSalida__c</fullName>
    <description>Fecha en la que el residente deja la plaza</description>
    <label>Fecha de salida</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de la oportunidad. Viene con el valor de espisodio en SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResidenciaIngreso__c.field-meta.xml
<CustomField>
    <fullName>ResidenciaIngreso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Centro al que ingresa el residente en esta oportunidad</description>
    <label>Residencia de ingreso</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroResidencia</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Residencia de Ingreso)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Parentesco.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B</fullName>
        <label>Hermano/a</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Cuñado/a</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cónyuge</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Pareja de hecho</label>
    </customValue>
    <customValue>
        <fullName>K</fullName>
        <label>Hijo/a</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>Otro familiar</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Nieto</label>
    </customValue>
    <customValue>
        <fullName>O</fullName>
        <label>Tío/a</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>Padre/Madre</label>
    </customValue>
    <customValue>
        <fullName>Q</fullName>
        <label>Sobrino</label>
    </customValue>
    <customValue>
        <fullName>R</fullName>
        <label>Nuera/ Yerno</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Profesional</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Tutor/a</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>No aporta</label>
    </customValue>
    <customValue>
        <fullName>X</fullName>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Yerno</label>
    </customValue>
    <description>Parentesco o relacion del contacto familiar/ allegado con el residente</description>
    <masterLabel>Parentesco/ Relación</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TriggerOpportunityContactHandler.cls
/**
@description
Handler del trigger TriggerOpportunityContact

DATE 		AUTHOR 		DESCRIPTION
03/09/2024	LCS - MSA	Creation

@author Leadclic Solutions
@date 03/09/2024
*/

public class TriggerOpportunityContactHandler {
    public void treatContactInformation(List<OpportunityContactRole> triggerNew) {
        if(triggerNew[0].Role != 'Residente'){
            List<OpportunityContactRole> residentOcr = [SELECT Id, Contact.IdExternoSAP__c, 
                                                    Opportunity.ResidenciaIngreso__r.CodigoCentroSAP__c 
                                                    FROM OpportunityContactRole 
                                                    WHERE OpportunityId = :triggerNew[0].OpportunityId AND Role ='Residente'
                                                    AND Opportunity.IdExternoSAP__c != null AND Opportunity.FechaSalida__c = null
                                                    AND (Opportunity.StageName = 'Cerrada - Éxito' OR Opportunity.StageName = 'Envío SAP')];

                                                    
                Contact familiar = [SELECT Id, FirstName, LastName, Salutation, Parentesco__c, MailingStreet,
                                    MailingPostalCode, MailingCity, MobilePhone, RecordType.DeveloperName,
                                    Email FROM Contact WHERE Id = :triggerNew[0].ContactId];

            if(residentOcr.size() > 0){
                ConectorFamiliares.sendContact(ConectorFamiliares.prepareDataToSend(familiar, residentOcr[0].Contact.IdExternoSAP__c, residentOcr[0].Opportunity.ResidenciaIngreso__r.CodigoCentroSAP__c), familiar.Id);
            }
        }
        
    }
}