force-app/main/default/objects/Account/fields/CodigoCentroSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoCentroSAP__c</fullName>
    <description>Identificador único del centro en SAP</description>
    <externalId>true</externalId>
    <label>Código del centro</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CentroResidencia.recordType-meta.xml
<RecordType>
    <fullName>CentroResidencia</fullName>
    <active>true</active>
    <description>Tipo de registro para residencias o centros</description>
    <label>Centro/Residencia</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Agitacion__c.field-meta.xml
<CustomField>
    <fullName>Agitacion__c</fullName>
    <description>Nos dice si el residente tiene agitaciones</description>
    <label>Agitación</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SeleccionNecesidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Alergias__c.field-meta.xml
<CustomField>
    <fullName>Alergias__c</fullName>
    <description>Nos dice si el residente tiene alergias</description>
    <label>Alergias</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SeleccionNecesidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP para los residentes</description>
    <externalId>true</externalId>
    <label>Identificador de SAP Residentes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NumeroDocumento__c.field-meta.xml
<CustomField>
    <fullName>NumeroDocumento__c</fullName>
    <description>Número de indentificación del residente</description>
    <label>Número del documento</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Oxigeno__c.field-meta.xml
<CustomField>
    <fullName>Oxigeno__c</fullName>
    <description>Nos dice si el residente necesita oxígeno</description>
    <label>Oxígeno</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SeleccionNecesidades</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Parentesco__c.field-meta.xml
<CustomField>
    <fullName>Parentesco__c</fullName>
    <description>Parentesco de la persona de contacto</description>
    <label>Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parentesco</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <description>Genero del residente: hombre o mujer</description>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genero</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación del residente</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>Pasaporte</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>NIE</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>DNI</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/PotencialResidente.recordType-meta.xml
<RecordType>
    <fullName>PotencialResidente</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo residente</description>
    <label>Potencial/Residente</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DetalleMotivoIngreso__c.field-meta.xml
<CustomField>
    <fullName>DetalleMotivoIngreso__c</fullName>
    <description>Campo de tipo lista de selección para conocer el detalle motivo de ingreso</description>
    <label>Detalle Motivo de Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MotivoIngreso__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>DetalleMotivoIngreso</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaIngresoPlanificado__c.field-meta.xml
<CustomField>
    <fullName>FechaIngresoPlanificado__c</fullName>
    <description>Fecha en la que se planifica que ingrese el paciente en la residencia</description>
    <inlineHelpText>Fecha probable de ingreso</inlineHelpText>
    <label>Fecha de Ingreso Planificado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de la oportunidad. Viene con el valor de espisodio en SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MotivoIngreso__c.field-meta.xml
<CustomField>
    <fullName>MotivoIngreso__c</fullName>
    <description>Campo de tipo lista de selección para conocer el motivo de ingreso</description>
    <label>Motivo de Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MotivoIngreso</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plaza que ocupa el paciente en la residencia</description>
    <label>Plaza residencia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Residencia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ResidenciaIngreso__c</valueField>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Plaza residencia)</relationshipLabel>
    <relationshipName>Oportunidades7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaJueves__c.field-meta.xml
<CustomField>
    <fullName>PlazaJueves__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Jueves en el centro de día ha de rellenarse este campo</description>
    <label>Jueves</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Jueves</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Jueves)</relationshipLabel>
    <relationshipName>Oportunidades3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaLunes__c.field-meta.xml
<CustomField>
    <fullName>PlazaLunes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Lunes en el centro de día ha de rellenarse este campo</description>
    <label>Lunes</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Lunes</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Lunes)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaMartes__c.field-meta.xml
<CustomField>
    <fullName>PlazaMartes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Martes en el centro de día ha de rellenarse este campo</description>
    <label>Martes</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Martes</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Martes)</relationshipLabel>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PlazaMiercoles__c.field-meta.xml
<CustomField>
    <fullName>PlazaMiercoles__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Si ocupa plaza el Miercoles en el centro de día ha de rellenarse este campo</description>
    <label>Miércoles</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.DiaSemana__c</field>
            <operation>equals</operation>
            <value>Miércoles</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroDia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Miércoles)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResidenciaIngreso__c.field-meta.xml
<CustomField>
    <fullName>ResidenciaIngreso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Centro al que ingresa el residente en esta oportunidad</description>
    <label>Residencia de ingreso</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroResidencia</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Residencia de Ingreso)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoPlaza__c.field-meta.xml
<CustomField>
    <fullName>TipoPlaza__c</fullName>
    <description>Tipo de plaza que se está negociando</description>
    <label>Tipo de plaza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoPlaza</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PlazaPrivada.recordType-meta.xml
<RecordType>
    <fullName>PlazaPrivada</fullName>
    <active>true</active>
    <businessProcess>Plaza privada</businessProcess>
    <description>Tipo de registro para el proceso de ventas de las plazas privadas</description>
    <label>Plaza privada</label>
</RecordType>

force-app/main/default/objects/Plaza__c/Plaza__c.object-meta.xml
<CustomObject>
    <description>En el objeto Plaza se recogerá toda la información de estructura, de módulos y de distribución de habitaciones y camas de los centros/ residencia así como de las plazas de Centro de día</description>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de Plaza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plaza__c/fields/Cama__c.field-meta.xml
<CustomField>
    <fullName>Cama__c</fullName>
    <description>Código de la cama</description>
    <label>Cama</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plaza__c/fields/Cuenta__c.field-meta.xml
<CustomField>
    <fullName>Cuenta__c</fullName>
    <description>Centro al que pertenece la plaza</description>
    <label>Centro</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plazas</relationshipLabel>
    <relationshipName>Plazas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Plaza__c/fields/DiaSemana__c.field-meta.xml
<CustomField>
    <fullName>DiaSemana__c</fullName>
    <description>Día de la semana</description>
    <label>Día de la semana</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lunes</fullName>
            </value>
            <value>
                <fullName>Martes</fullName>
            </value>
            <value>
                <fullName>Miércoles</fullName>
            </value>
            <value>
                <fullName>Jueves</fullName>
            </value>
            <value>
                <fullName>Viernes</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plaza__c/fields/TipoPlaza__c.field-meta.xml
<CustomField>
    <fullName>TipoPlaza__c</fullName>
    <description>Indica si la plaza está ocupada por una plaza pública o privada. Solo se rellena en las plazas ocupadas, las libres no tienen esta caracteristica.</description>
    <label>Tipo de plaza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoPlaza</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plaza__c/recordTypes/CentroDia.recordType-meta.xml
<RecordType>
    <fullName>CentroDia</fullName>
    <active>true</active>
    <description>Tipo de registro para las plazas de centro de día</description>
    <label>Centro de día</label>
</RecordType>

force-app/main/default/objects/Plaza__c/recordTypes/Residencia.recordType-meta.xml
<RecordType>
    <fullName>Residencia</fullName>
    <active>true</active>
    <description>Tipo de registro para las plazas de residencia</description>
    <label>Residencia</label>
</RecordType>

force-app/main/default/globalValueSets/DetalleMotivoIngreso.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Autolisis</fullName>
    </customValue>
    <customValue>
        <fullName>Bipolar</fullName>
    </customValue>
    <customValue>
        <fullName>Depresión / Ansiedad</fullName>
    </customValue>
    <customValue>
        <fullName>Enfermedad neurológica</fullName>
    </customValue>
    <customValue>
        <fullName>Esquizofrenia</fullName>
    </customValue>
    <customValue>
        <fullName>TOC</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>ACV / Ictus</fullName>
    </customValue>
    <customValue>
        <fullName>Amputación</fullName>
    </customValue>
    <customValue>
        <fullName>Caídas</fullName>
    </customValue>
    <customValue>
        <fullName>Cáncer</fullName>
    </customValue>
    <customValue>
        <fullName>Esclerosis</fullName>
    </customValue>
    <customValue>
        <fullName>Fractura</fullName>
    </customValue>
    <customValue>
        <fullName>Problemas cardiovasculares (Infarto, ICC, HTA, Arritmias, Fibrilación, Diabetes…)</fullName>
    </customValue>
    <customValue>
        <fullName>Movilidad reducida</fullName>
    </customValue>
    <customValue>
        <fullName>Paliativos</fullName>
    </customValue>
    <customValue>
        <fullName>Parkinson</fullName>
    </customValue>
    <customValue>
        <fullName>Operación / Convalecencia</fullName>
    </customValue>
    <customValue>
        <fullName>Problemas respiratorios (O2, Neutomonía, EPOC...)</fullName>
    </customValue>
    <customValue>
        <fullName>Otras</fullName>
    </customValue>
    <customValue>
        <fullName>Alteraciones de conducta</fullName>
    </customValue>
    <customValue>
        <fullName>Alzheimer</fullName>
    </customValue>
    <customValue>
        <fullName>Cuerpo Lewy</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia fronto-temporal</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia senil</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia vascular</fullName>
    </customValue>
    <customValue>
        <fullName>Desorientación / Riesgo fuga</fullName>
    </customValue>
    <customValue>
        <fullName>Perdidas memoria</fullName>
    </customValue>
    <customValue>
        <fullName>ELA</fullName>
    </customValue>
    <customValue>
        <fullName>De la competencia por descontento</fullName>
    </customValue>
    <description>Valores del campo Detalle Motivo de Ingreso del Lead y Opp</description>
    <masterLabel>Detalle Motivo de Ingreso</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Genero.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Hombre</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Mujer</label>
    </customValue>
    <description>Genero del residente: hombre o mujer</description>
    <masterLabel>Género</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MotivoIngreso.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Psicogeriatría</fullName>
    </customValue>
    <customValue>
        <fullName>Dependencia cognitiva</fullName>
    </customValue>
    <customValue>
        <fullName>Dependencia física</fullName>
    </customValue>
    <customValue>
        <fullName>Dependencia física y cognitiva</fullName>
    </customValue>
    <customValue>
        <fullName>Aspectos sociales</fullName>
    </customValue>
    <customValue>
        <fullName>Traslado residencia</fullName>
    </customValue>
    <customValue>
        <fullName>Plaza Pública</fullName>
    </customValue>
    <description>Valores de motivo de ingreso en Leads y Opps</description>
    <masterLabel>Motivo de Ingreso</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Parentesco.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B</fullName>
        <label>Hermano/a</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Cuñado/a</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cónyuge</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Pareja de hecho</label>
    </customValue>
    <customValue>
        <fullName>K</fullName>
        <label>Hijo/a</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>Otro familiar</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Nieto</label>
    </customValue>
    <customValue>
        <fullName>O</fullName>
        <label>Tío/a</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>Padre/Madre</label>
    </customValue>
    <customValue>
        <fullName>Q</fullName>
        <label>Sobrino</label>
    </customValue>
    <customValue>
        <fullName>R</fullName>
        <label>Nuera/ Yerno</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Profesional</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Tutor/a</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>No aporta</label>
    </customValue>
    <customValue>
        <fullName>X</fullName>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Yerno</label>
    </customValue>
    <description>Parentesco o relacion del contacto familiar/ allegado con el residente</description>
    <masterLabel>Parentesco/ Relación</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SeleccionNecesidades.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>NS/NC</fullName>
        <default>true</default>
        <label>NS/NC</label>
    </customValue>
    <customValue>
        <fullName>Sí</fullName>
    </customValue>
    <customValue>
        <fullName>No</fullName>
    </customValue>
    <description>Para los campos que tengan si, no y no seleccionado</description>
    <masterLabel>Seleccion Necesidades</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TipoPlaza.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P</fullName>
        <label>Privada</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Pública</label>
    </customValue>
    <description>Tipo de plaza que se solicita</description>
    <masterLabel>Tipo de plaza</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestTriggerOpportunityHandler.cls
/**
@description
Test Methods de la clase TriggerOpportunityHandler

DATE 		AUTHOR 		DESCRIPTION
14/09/2023  MSA - LCS   Correccion parentesco
22/05/2023  MSA - LCS   Corrección errores por el nuevo cambio en las oportunidades
10/10/2022  LCS - MSA   Comentado el test testFalloSinDocumento para evitar los fallos.
21/09/2022  LCS - MSA   Correcciones para evitar los fallos.
19/01/2022  LCS - MMV   Correcciones para evitar los fallos.
05/08/2021	LCS - MMV	Creation

@author Leadclic Solutions
@date 05/08/2021 
*/
@isTest 
public class TestTriggerOpportunityHandler {

    // Obtenemos los Identificador de los tipos de registros necesarios
    private static final Id accountCentroRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CentroResidencia').getRecordTypeId();
    private static final Id plazaResidenciaRTId = Schema.SObjectType.Plaza__c.getRecordTypeInfosByDeveloperName().get('Residencia').getRecordTypeId();
    private static final Id plazaCentroDiaRTId = Schema.SObjectType.Plaza__c.getRecordTypeInfosByDeveloperName().get('CentroDia').getRecordTypeId();
    private static final Id accountFamiliaRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('FamiliaAllegado').getRecordTypeId();
    private static final Id contactFamiliarRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('FamiliaAllegado').getRecordTypeId();
    private static final Id contactResidenteRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('PotencialResidente').getRecordTypeId();
    private static final Id opportunityPlazaPrivadaRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('PlazaPrivada').getRecordTypeId();

    @TestSetup
    static void setup(){        

        // Damos de alta un centro
        Account centro = new Account(
            Name = 'Centro de prueba',
            RecordTypeId = accountCentroRTId,
            CodigoCentroSAP__c = '2808'
        );
        insert centro;

        // Creamos una plaza para ese centro
        List<Plaza__c> lPlazas = new List<Plaza__c>();
        Plaza__c plazaResi = new Plaza__c (
            Name = '2808H0101',
            RecordTypeId = plazaResidenciaRTId,
            Cama__c = '2808H0101',
            Cuenta__c = centro.Id
        );
        lPlazas.add(plazaResi);
        // Creamos plazas de centro de día para ese centro        
        Plaza__c plazaCDLunes = new Plaza__c (
            Name = '2808CDC0101L',
            RecordTypeId = plazaCentroDiaRTId,
            Cama__c = '2808CDC0101L',
            Cuenta__c = centro.Id,
            DiaSemana__c = 'Lunes'
        );
        lPlazas.add(plazaCDLunes);
        Plaza__c plazaCDMartes = new Plaza__c (
            Name = '2808CDC0101M',
            RecordTypeId = plazaCentroDiaRTId,
            Cama__c = '2808CDC0101M',
            Cuenta__c = centro.Id,
            DiaSemana__c = 'Martes'
        );
        lPlazas.add(plazaCDMartes);
        Plaza__c plazaCDMiercoles = new Plaza__c (
            Name = '2808CDC0101X',
            RecordTypeId = plazaCentroDiaRTId,
            Cama__c = '2808CDC0101X',
            Cuenta__c = centro.Id,
            DiaSemana__c = 'Miércoles'
        );
        lPlazas.add(plazaCDMiercoles);
        Plaza__c plazaCDJueves = new Plaza__c (
            Name = '2808CDC0101J',
            RecordTypeId = plazaCentroDiaRTId,
            Cama__c = '2808CDC0101J',
            Cuenta__c = centro.Id,
            DiaSemana__c = 'Jueves'
        );
        lPlazas.add(plazaCDJueves);
        Plaza__c plazaCDViernes = new Plaza__c (
            Name = '2808CDC0101V',
            RecordTypeId = plazaCentroDiaRTId,
            Cama__c = '2808CDC0101V',
            Cuenta__c = centro.Id,
            DiaSemana__c = 'Viernes'
        );
        lPlazas.add(plazaCDViernes);
        Plaza__c plazaCDSabado = new Plaza__c (
            Name = '2808CDC0101S',
            RecordTypeId = plazaCentroDiaRTId,
            Cama__c = '2808CDC0101S',
            Cuenta__c = centro.Id,
            DiaSemana__c = 'Sábado'
        );
        lPlazas.add(plazaCDSabado);
        Plaza__c plazaCDDomingo = new Plaza__c (
            Name = '2808CDC0101D',
            RecordTypeId = plazaCentroDiaRTId,
            Cama__c = '2808CDC0101D',
            Cuenta__c = centro.Id,
            DiaSemana__c = 'Domingo'
        );
        lPlazas.add(plazaCDDomingo);
        insert lPlazas;

        //Insertamos una cuenta para relacionar la oportunidad
        Account familia = new Account(
            Name = 'CuentaFamilia',
            RecordTypeId = accountFamiliaRTId
        );
        insert familia;

        //Generamos un contacto como residente y dos familiares
        List <Contact> lCont2Insert = new List <Contact>();
        Contact residente = new Contact(
            RecordTypeId = contactResidenteRTId,
            AccountId = familia.Id,
            Birthdate = Date.Today()-1,
            IdExternoSAP__c='9999',
            FirstName='ResidentePrueba',
            LastName='ApellidoPruebaResidente',
            MailingStreet='Ancha',
            MailingPostalCode='28005',
            MailingCity='Madrid',
            MobilePhone='602275300',
            Phone='917390566',
            Email='mailresidente@test.com',
            Sexo__c = '2',
            TipoDocumento__c = '01',
            NumeroDocumento__c = '02796904N',
            Oxigeno__c = 'NS/NC',
            SuplementoNutricional__c = 'NS/NC',
            SondaNasogastrica__c = 'NS/NC',
            SondaVesical__c = 'NS/NC',
            Sujeccion__c = 'NS/NC',
            Alergias__c = 'NS/NC',
            ProblemasDeDeglucion__c = 'NS/NC',
            Incontinencia__c = 'NS/NC',
            Agitacion__c = 'NS/NC',
            Vagabundeo__c = 'NS/NC',
            RiesgoDeFuga__c = 'NS/NC',
            Desorientado__c = 'NS/NC'
        );
        lCont2Insert.add(residente);
        
        Contact familiar1 = new Contact(
            RecordTypeId = contactFamiliarRTId,
            AccountId = familia.Id,
            IdExternoSAP__c='8888',
            FirstName='FamiliarPrueba',
            LastName='ApellidoPruebafamiliar1Decisor',
            MailingStreet='Ancha',
            MailingPostalCode='28005',
            MailingCity='Madrid',
            MobilePhone='602275300',
            Phone='917390566',
            Email='mailfmailiar1@test.com',
            Parentesco__c = 'K'
        );
        lCont2Insert.add(familiar1);

        Contact familiar2 = new Contact(
            RecordTypeId = contactFamiliarRTId,
            AccountId = familia.Id,
            IdExternoSAP__c='7777',
            FirstName='FamiliarPrueba',
            LastName='ApellidoFamiliar2Influyente',
            MailingStreet='Ancha',
            MailingPostalCode='28005',
            MailingCity='Madrid',
            MobilePhone='602275300',
            Phone='917390566',
            Email='mailfamiliar2@test.com',
            Parentesco__c = 'K'
        );
        lCont2Insert.add(familiar2);
        
        Contact familiar3 = new Contact(
            RecordTypeId = contactFamiliarRTId,
            AccountId = familia.Id,
            IdExternoSAP__c='3333',
            FirstName='FamiliarPrueba',
            LastName='ApellidoPruebaFamiliar3Decisor',
            MailingStreet='Ancha',
            MailingPostalCode='28003',
            MailingCity='Madrid',
            MobilePhone='603375300',
            Phone='917390533',
            Email='mailfamiliar3@test.com',
            Parentesco__c = 'K'
        );
        lCont2Insert.add(familiar3);

        // Insertamos los contactos
        insert lCont2Insert;

        // Insertamos una oportunidad
        Opportunity oportunidad = new Opportunity(
            AccountId = familia.Id,
            Name = 'Oportunidad de prueba',
            RecordTypeId = opportunityPlazaPrivadaRTId,
            StageName = Opportunity.StageName.getDescribe().getPicklistValues()[0].getValue(),
            CloseDate = Date.today(),
            ResidenciaIngreso__c = centro.Id,
            Plaza__c = plazaResi.Id,
            TipoPlaza__c = 'P',
            FechaIngresoPlanificado__c = Date.today(),
            MotivoIngreso__c = 'Psicogeriatría',
            DetalleMotivoIngreso__c = 'Autolisis'
        );
        insert oportunidad;

        // NO insertamos los roles de los contactos en la oportunidad porque hay un flujo que automáticamente los inserta
        /*List<OpportunityContactRole> lOcr = new List<OpportunityContactRole> ();
        OpportunityContactRole ocrResidente = new OpportunityContactRole (
            OpportunityId = oportunidad.Id,
            ContactId = residente.Id,
            Role = 'Residente'
        );
        lOcr.add(ocrResidente);

        OpportunityContactRole ocrFamiliar1 = new OpportunityContactRole (
            OpportunityId = oportunidad.Id,
            ContactId = familiar1.Id,
            Role = 'Decisor'
        );
        lOcr.add(ocrFamiliar1);
        
        OpportunityContactRole ocrFamiliar3 = new OpportunityContactRole (
            OpportunityId = oportunidad.Id,
            ContactId = familiar3.Id,
            Role = 'Decisor'
        );
        lOcr.add(ocrFamiliar3);

        OpportunityContactRole ocrFamiliar2 = new OpportunityContactRole (
            OpportunityId = oportunidad.Id,
            ContactId = familiar2.Id,
            Role = 'Influyente'
        );
        lOcr.add(ocrFamiliar2);

        insert lOcr;*/

    }

    /**
    @description    Método para probar el cierre de una oportunidad.
    @param          
    @return         
    */
    @isTest 
    static void testCierreOportunidadOK(){

        Opportunity lOpp = [SELECT Id FROM Opportunity LIMIT 1];

        test.startTest();

        Test.setMock(HttpCalloutMock.class, new WSSAPAdmisionesMock('<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">    <soap-env:Header/>    <soap-env:Body>        <n0:ZISH_CREAR_ADMISION_SFResponse xmlns:n0="urn:sap-com:document:sap:rfc:functions">            <E_FALNR/>            <E_PARTNER1>0010055442</E_PARTNER1>            <E_PARTNER2/>            <E_PATNR>0000038199</E_PATNR>            <E_RETURN>                <item>                    <TYPE>S</TYPE>                    <MESSAGE>El paciente 0000038199 no se ha creado ya que existe en el sistema</MESSAGE>                </item>                <item>                    <TYPE>E</TYPE>                    <MESSAGE>Indique una fecha de movimiento</MESSAGE>                </item>            </E_RETURN>        </n0:ZISH_CREAR_ADMISION_SFResponse>    </soap-env:Body></soap-env:Envelope>'));

        TriggerOpportunityHandler.prepareDataCall(new List<Id>{lOpp.Id});

        test.stopTest();        
    }
       

    /**
    @description    Método para probar el cierre de una oportunidad con plazas de centro de día.
    @param          
    @return         
    */
    @isTest 
    static void testCierreOportunidadCentroDiaOK(){

        Opportunity opp = [SELECT Id, PlazaLunes__c, PlazaMartes__c, 
        PlazaMiercoles__c, PlazaJueves__c, PlazaViernes__c, PlazaSabado__c,
        PlazaDomingo__c FROM Opportunity LIMIT 1];
        List<Plaza__c> lPlazas = [SELECT Id, DiaSemana__c, Cama__c FROM Plaza__c WHERE RecordTypeId =: plazaCentroDiaRTId];
        
        // Quitamos la plaza de residencia y añadimos la plazas de centro de día
        opp.Plaza__c = null;
        for(Plaza__c pl : lPlazas){
            opp.PlazaLunes__c = pl.DiaSemana__c == 'Lunes' ? pl.Id : opp.PlazaLunes__c;
            opp.PlazaMartes__c = pl.DiaSemana__c == 'Martes' ? pl.Id : opp.PlazaMartes__c;
            opp.PlazaMiercoles__c = pl.DiaSemana__c == 'Miércoles' ? pl.Id : opp.PlazaMiercoles__c;
            opp.PlazaJueves__c = pl.DiaSemana__c == 'Jueves' ? pl.Id : opp.PlazaJueves__c;
            opp.PlazaViernes__c = pl.DiaSemana__c == 'Viernes' ? pl.Id : opp.PlazaViernes__c;
            opp.PlazaSabado__c = pl.DiaSemana__c == 'Sábado' ? pl.Id : opp.PlazaSabado__c;
            opp.PlazaDomingo__c = pl.DiaSemana__c == 'Domingo' ? pl.Id : opp.PlazaDomingo__c;
        }
        update opp;

        test.startTest();

        Test.setMock(HttpCalloutMock.class, new WSSAPAdmisionesMock('<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">    <soap-env:Header/>    <soap-env:Body>        <n0:ZISH_CREAR_ADMISION_SFResponse xmlns:n0="urn:sap-com:document:sap:rfc:functions">            <E_FALNR/>            <E_PARTNER1>0010055442</E_PARTNER1>            <E_PARTNER2/>            <E_PATNR>0000038199</E_PATNR>            <E_RETURN>                <item>                    <TYPE>S</TYPE>                    <MESSAGE>El paciente 0000038199 no se ha creado ya que existe en el sistema</MESSAGE>                </item>                <item>                    <TYPE>E</TYPE>                    <MESSAGE>Indique una fecha de movimiento</MESSAGE>                </item>            </E_RETURN>        </n0:ZISH_CREAR_ADMISION_SFResponse>    </soap-env:Body></soap-env:Envelope>'));

        TriggerOpportunityHandler.prepareDataCall(new List<Id>{opp.Id});

        test.stopTest();        
    }

    /**
    @description    Método para probar el fallo cuando el residente no tiene Género.
    @param          
    @return         
    */
    @isTest 
    static void testFalloSinGenero(){
        
        // Obtenemos el mensaje de error de Salesforce para compararlo con el resultado
        Mensaje_Error__mdt mensajeError = Mensaje_Error__mdt.getInstance('CierraOportunidadSinGenero');

        Opportunity lOpp = [SELECT Id FROM Opportunity LIMIT 1];

        // Obtenemos el contacto residente para cambiar o vaciar los campos a validar
        Contact residente = [SELECT Id, FirstName, Sexo__c,
                             NumeroDocumento__c,MailingStreet,MailingPostalCode,MailingCity 
                             FROM Contact 
                             WHERE Email = 'mailresidente@test.com' LIMIT 1];        
                             
        // Le quitamos el campo al contacto
        residente.Sexo__c = null;
        update residente;

        test.startTest();

        Test.setMock(HttpCalloutMock.class, new WSSAPAdmisionesMock('<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">    <soap-env:Header/>    <soap-env:Body>        <n0:ZISH_CREAR_ADMISION_SFResponse xmlns:n0="urn:sap-com:document:sap:rfc:functions">            <E_FALNR/>            <E_PARTNER1>0010055442</E_PARTNER1>            <E_PARTNER2/>            <E_PATNR>0000038199</E_PATNR>            <E_RETURN>                <item>                    <TYPE>S</TYPE>                    <MESSAGE>El paciente 0000038199 no se ha creado ya que existe en el sistema</MESSAGE>                </item>                <item>                    <TYPE>E</TYPE>                    <MESSAGE>Indique una fecha de movimiento</MESSAGE>                </item>            </E_RETURN>        </n0:ZISH_CREAR_ADMISION_SFResponse>    </soap-env:Body></soap-env:Envelope>'));

        try{
            TriggerOpportunityHandler.prepareDataCall(new List<Id>{lOpp.Id});
        }catch (TriggerOpportunityHandler.CerrarOportunidadException e){
            // Comprobamos que ha salido el mensaje de error correcto
            system.assertEquals(mensajeError.Error_Description__c, e.getMessage());
        }

        test.stopTest();           
    }
    /**
    @description    Método para probar el fallo cuando el residente no tiene NumeroDocumento__c.
    @param          
    @return         

    @isTest 
    static void testFalloSinDocumento(){

        // Obtenemos el mensaje de error de Salesforce para compararlo con el resultado
        Mensaje_Error__mdt mensajeError = Mensaje_Error__mdt.getInstance('CierraOportunidadSinDocumento');

        Opportunity lOpp = [SELECT Id FROM Opportunity LIMIT 1];

        // Obtenemos el contacto residente para cambiar o vaciar los campos a validar
        Contact residente = [SELECT Id, FirstName, Sexo__c,
                             NumeroDocumento__c,MailingStreet,MailingPostalCode,MailingCity 
                             FROM Contact 
                             WHERE Email = 'mailresidente@test.com' LIMIT 1];        
                             
        // Le quitamos el campo al contacto
        residente.NumeroDocumento__c = null;
        update residente;

        test.startTest();

        Test.setMock(HttpCalloutMock.class, new WSSAPAdmisionesMock('<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">    <soap-env:Header/>    <soap-env:Body>        <n0:ZISH_CREAR_ADMISION_SFResponse xmlns:n0="urn:sap-com:document:sap:rfc:functions">            <E_FALNR/>            <E_PARTNER1>0010055442</E_PARTNER1>            <E_PARTNER2/>            <E_PATNR>0000038199</E_PATNR>            <E_RETURN>                <item>                    <TYPE>S</TYPE>                    <MESSAGE>El paciente 0000038199 no se ha creado ya que existe en el sistema</MESSAGE>                </item>                <item>                    <TYPE>E</TYPE>                    <MESSAGE>Indique una fecha de movimiento</MESSAGE>                </item>            </E_RETURN>        </n0:ZISH_CREAR_ADMISION_SFResponse>    </soap-env:Body></soap-env:Envelope>'));

        try{
            TriggerOpportunityHandler.prepareDataCall(new List<Id>{lOpp.Id});
        }catch (TriggerOpportunityHandler.CerrarOportunidadException e){
            // Comprobamos que ha salido el mensaje de error correcto
            system.assertEquals(mensajeError.Error_Description__c, e.getMessage());
        }

        test.stopTest();           
    }
    */
    
    /**
    @description    Método para probar el fallo cuando el residente no tiene MailingStreet.
    @param          
    @return         
    */
    @isTest 
    static void testFalloSinCalle(){

        // Obtenemos el mensaje de error de Salesforce para compararlo con el resultado
        Mensaje_Error__mdt mensajeError = Mensaje_Error__mdt.getInstance('CierraOportunidadSinCalle');

        Opportunity lOpp = [SELECT Id FROM Opportunity LIMIT 1];

        // Obtenemos el contacto residente para cambiar o vaciar los campos a validar
        Contact residente = [SELECT Id, FirstName, Sexo__c,
                             NumeroDocumento__c,MailingStreet,MailingPostalCode,MailingCity 
                             FROM Contact 
                             WHERE Email = 'mailresidente@test.com' LIMIT 1];        
                             
        // Le quitamos el campo al contacto
        residente.MailingStreet = null;
        update residente;

        test.startTest();

        Test.setMock(HttpCalloutMock.class, new WSSAPAdmisionesMock('<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">    <soap-env:Header/>    <soap-env:Body>        <n0:ZISH_CREAR_ADMISION_SFResponse xmlns:n0="urn:sap-com:document:sap:rfc:functions">            <E_FALNR/>            <E_PARTNER1>0010055442</E_PARTNER1>            <E_PARTNER2/>            <E_PATNR>0000038199</E_PATNR>            <E_RETURN>                <item>                    <TYPE>S</TYPE>                    <MESSAGE>El paciente 0000038199 no se ha creado ya que existe en el sistema</MESSAGE>                </item>                <item>                    <TYPE>E</TYPE>                    <MESSAGE>Indique una fecha de movimiento</MESSAGE>                </item>            </E_RETURN>        </n0:ZISH_CREAR_ADMISION_SFResponse>    </soap-env:Body></soap-env:Envelope>'));

        try{
            TriggerOpportunityHandler.prepareDataCall(new List<Id>{lOpp.Id});
        }catch (TriggerOpportunityHandler.CerrarOportunidadException e){
            // Comprobamos que ha salido el mensaje de error correcto
            system.assertEquals(mensajeError.Error_Description__c, e.getMessage());
        }

        test.stopTest();           
    }

    /**
    @description    Método para probar el fallo cuando el residente no tiene MailingPostalCode.
    @param          
    @return         
    */
    @isTest 
    static void testFalloSinCodigoPostal(){

        // Obtenemos el mensaje de error de Salesforce para compararlo con el resultado
        Mensaje_Error__mdt mensajeError = Mensaje_Error__mdt.getInstance('CierraOportunidadSinCodigoPostal');

        Opportunity lOpp = [SELECT Id FROM Opportunity LIMIT 1];

        // Obtenemos el contacto residente para cambiar o vaciar los campos a validar
        Contact residente = [SELECT Id, FirstName, Sexo__c,
                             NumeroDocumento__c,MailingStreet,MailingPostalCode,MailingCity 
                             FROM Contact 
                             WHERE Email = 'mailresidente@test.com' LIMIT 1];        
                             
        // Le quitamos el campo al contacto
        residente.MailingPostalCode = null;
        update residente;

        test.startTest();

        Test.setMock(HttpCalloutMock.class, new WSSAPAdmisionesMock('<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">    <soap-env:Header/>    <soap-env:Body>        <n0:ZISH_CREAR_ADMISION_SFResponse xmlns:n0="urn:sap-com:document:sap:rfc:functions">            <E_FALNR/>            <E_PARTNER1>0010055442</E_PARTNER1>            <E_PARTNER2/>            <E_PATNR>0000038199</E_PATNR>            <E_RETURN>                <item>                    <TYPE>S</TYPE>                    <MESSAGE>El paciente 0000038199 no se ha creado ya que existe en el sistema</MESSAGE>                </item>                <item>                    <TYPE>E</TYPE>                    <MESSAGE>Indique una fecha de movimiento</MESSAGE>                </item>            </E_RETURN>        </n0:ZISH_CREAR_ADMISION_SFResponse>    </soap-env:Body></soap-env:Envelope>'));

        try{
            TriggerOpportunityHandler.prepareDataCall(new List<Id>{lOpp.Id});
        }catch (TriggerOpportunityHandler.CerrarOportunidadException e){
            // Comprobamos que ha salido el mensaje de error correcto
            system.assertEquals(mensajeError.Error_Description__c, e.getMessage());
        }

        test.stopTest();           
    }

    /**
    @description    Método para probar el fallo cuando el residente no tiene MailingCity.
    @param          
    @return         
    */
    @isTest 
    static void testFalloSinCiudad(){

        // Obtenemos el mensaje de error de Salesforce para compararlo con el resultado
        Mensaje_Error__mdt mensajeError = Mensaje_Error__mdt.getInstance('CierraOportunidadSinCiudad');

        Opportunity lOpp = [SELECT Id FROM Opportunity LIMIT 1];

        // Obtenemos el contacto residente para cambiar o vaciar los campos a validar
        Contact residente = [SELECT Id, FirstName, Sexo__c,
                             NumeroDocumento__c,MailingStreet,MailingPostalCode,MailingCity 
                             FROM Contact 
                             WHERE Email = 'mailresidente@test.com' LIMIT 1];        
                             
        // Le quitamos el campo al contacto
        residente.MailingCity = null;
        update residente;

        test.startTest();

        Test.setMock(HttpCalloutMock.class, new WSSAPAdmisionesMock('<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">    <soap-env:Header/>    <soap-env:Body>        <n0:ZISH_CREAR_ADMISION_SFResponse xmlns:n0="urn:sap-com:document:sap:rfc:functions">            <E_FALNR/>            <E_PARTNER1>0010055442</E_PARTNER1>            <E_PARTNER2/>            <E_PATNR>0000038199</E_PATNR>            <E_RETURN>                <item>                    <TYPE>S</TYPE>                    <MESSAGE>El paciente 0000038199 no se ha creado ya que existe en el sistema</MESSAGE>                </item>                <item>                    <TYPE>E</TYPE>                    <MESSAGE>Indique una fecha de movimiento</MESSAGE>                </item>            </E_RETURN>        </n0:ZISH_CREAR_ADMISION_SFResponse>    </soap-env:Body></soap-env:Envelope>'));

        try{
            TriggerOpportunityHandler.prepareDataCall(new List<Id>{lOpp.Id});
        }catch (TriggerOpportunityHandler.CerrarOportunidadException e){
            // Comprobamos que ha salido el mensaje de error correcto
            system.assertEquals(mensajeError.Error_Description__c, e.getMessage());
        }

        test.stopTest();           
    }


    /**
    @description    Método para probar el fallo no hay ningún contacto residente asociado.
    @param          
    @return         
    */
    @isTest 
    static void testFalloSinResidente(){

        // Obtenemos el mensaje de error de Salesforce para compararlo con el resultado
        Mensaje_Error__mdt mensajeError = Mensaje_Error__mdt.getInstance('CierraOportunidadSinResidente');

        Opportunity lOpp = [SELECT Id FROM Opportunity LIMIT 1];

        // Probamos el fallo SIN RESIDENTE
        // Borramos los contactRole
        delete [SELECT Id FROM OpportunityContactRole];

        test.startTest();

        Test.setMock(HttpCalloutMock.class, new WSSAPAdmisionesMock('<soap-env:Envelope xmlns:soap-env="http://schemas.xmlsoap.org/soap/envelope/">    <soap-env:Header/>    <soap-env:Body>        <n0:ZISH_CREAR_ADMISION_SFResponse xmlns:n0="urn:sap-com:document:sap:rfc:functions">            <E_FALNR/>            <E_PARTNER1>0010055442</E_PARTNER1>            <E_PARTNER2/>            <E_PATNR>0000038199</E_PATNR>            <E_RETURN>                <item>                    <TYPE>S</TYPE>                    <MESSAGE>El paciente 0000038199 no se ha creado ya que existe en el sistema</MESSAGE>                </item>                <item>                    <TYPE>E</TYPE>                    <MESSAGE>Indique una fecha de movimiento</MESSAGE>                </item>            </E_RETURN>        </n0:ZISH_CREAR_ADMISION_SFResponse>    </soap-env:Body></soap-env:Envelope>'));

        try{
            TriggerOpportunityHandler.prepareDataCall(new List<Id>{lOpp.Id});
        }catch (TriggerOpportunityHandler.CerrarOportunidadException e){
            // Comprobamos que ha salido el mensaje de error correcto
            system.assertEquals(mensajeError.Error_Description__c, e.getMessage());
        }

        test.stopTest();        
    }

}