force-app/main/default/objects/Account/fields/CodigoCentroSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoCentroSAP__c</fullName>
    <description>Identificador único del centro en SAP</description>
    <externalId>true</externalId>
    <label>Código del centro</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/CentroResidencia.recordType-meta.xml
<RecordType>
    <fullName>CentroResidencia</fullName>
    <active>true</active>
    <description>Tipo de registro para residencias o centros</description>
    <label>Centro/Residencia</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP para los residentes</description>
    <externalId>true</externalId>
    <label>Identificador de SAP Residentes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NumeroDocumento__c.field-meta.xml
<CustomField>
    <fullName>NumeroDocumento__c</fullName>
    <description>Número de indentificación del residente</description>
    <label>Número del documento</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <description>Genero del residente: hombre o mujer</description>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genero</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación del residente</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>Pasaporte</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>NIE</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>DNI</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/PotencialResidente.recordType-meta.xml
<RecordType>
    <fullName>PotencialResidente</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo residente</description>
    <label>Potencial/Residente</label>
</RecordType>

force-app/main/default/objects/Event/recordTypes/Evento.recordType-meta.xml
<RecordType>
    <fullName>Evento</fullName>
    <active>true</active>
    <description>Eventos destinados a prescriptores y planificados</description>
    <label>Evento</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DetalleMotivoIngreso__c.field-meta.xml
<CustomField>
    <fullName>DetalleMotivoIngreso__c</fullName>
    <description>Campo de tipo lista de selección para conocer el detalle motivo de ingreso</description>
    <label>Detalle Motivo de Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MotivoIngreso__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>DetalleMotivoIngreso</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/FechaIngresoPlanificado__c.field-meta.xml
<CustomField>
    <fullName>FechaIngresoPlanificado__c</fullName>
    <description>Fecha en la que se planifica que ingrese el paciente en la residencia</description>
    <inlineHelpText>Fecha probable de ingreso</inlineHelpText>
    <label>Fecha de Ingreso Planificado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de la oportunidad. Viene con el valor de espisodio en SAP</description>
    <externalId>true</externalId>
    <label>Identificador de SAP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/MotivoIngreso__c.field-meta.xml
<CustomField>
    <fullName>MotivoIngreso__c</fullName>
    <description>Campo de tipo lista de selección para conocer el motivo de ingreso</description>
    <label>Motivo de Ingreso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MotivoIngreso</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plaza__c.field-meta.xml
<CustomField>
    <fullName>Plaza__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plaza que ocupa el paciente en la residencia</description>
    <label>Plaza residencia</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plaza__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Residencia</value>
        </filterItems>
        <filterItems>
            <field>Plaza__c.Cuenta__c</field>
            <operation>equals</operation>
            <valueField>$Source.ResidenciaIngreso__c</valueField>
        </filterItems>
        <filterItems>
            <field>Plaza__c.PlazaInhabilitada__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plaza__c</referenceTo>
    <relationshipLabel>Oportunidades (Plaza residencia)</relationshipLabel>
    <relationshipName>Oportunidades7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResidenciaIngreso__c.field-meta.xml
<CustomField>
    <fullName>ResidenciaIngreso__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Centro al que ingresa el residente en esta oportunidad</description>
    <label>Residencia de ingreso</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>CentroResidencia</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oportunidades (Residencia de Ingreso)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/TipoPlaza__c.field-meta.xml
<CustomField>
    <fullName>TipoPlaza__c</fullName>
    <description>Tipo de plaza que se está negociando</description>
    <label>Tipo de plaza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoPlaza</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/PlazaPrivada.recordType-meta.xml
<RecordType>
    <fullName>PlazaPrivada</fullName>
    <active>true</active>
    <businessProcess>Plaza privada</businessProcess>
    <description>Tipo de registro para el proceso de ventas de las plazas privadas</description>
    <label>Plaza privada</label>
</RecordType>

force-app/main/default/objects/Plaza__c/Plaza__c.object-meta.xml
<CustomObject>
    <description>En el objeto Plaza se recogerá toda la información de estructura, de módulos y de distribución de habitaciones y camas de los centros/ residencia así como de las plazas de Centro de día</description>
    <label>Plaza</label>
    <nameField>
        <label>Nombre de Plaza</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plazas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plaza__c/fields/TipoPlaza__c.field-meta.xml
<CustomField>
    <fullName>TipoPlaza__c</fullName>
    <description>Indica si la plaza está ocupada por una plaza pública o privada. Solo se rellena en las plazas ocupadas, las libres no tienen esta caracteristica.</description>
    <label>Tipo de plaza</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>TipoPlaza</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plaza__c/recordTypes/CentroDia.recordType-meta.xml
<RecordType>
    <fullName>CentroDia</fullName>
    <active>true</active>
    <description>Tipo de registro para las plazas de centro de día</description>
    <label>Centro de día</label>
</RecordType>

force-app/main/default/objects/Plaza__c/recordTypes/Residencia.recordType-meta.xml
<RecordType>
    <fullName>Residencia</fullName>
    <active>true</active>
    <description>Tipo de registro para las plazas de residencia</description>
    <label>Residencia</label>
</RecordType>

force-app/main/default/globalValueSets/DetalleMotivoIngreso.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Autolisis</fullName>
    </customValue>
    <customValue>
        <fullName>Bipolar</fullName>
    </customValue>
    <customValue>
        <fullName>Depresión / Ansiedad</fullName>
    </customValue>
    <customValue>
        <fullName>Enfermedad neurológica</fullName>
    </customValue>
    <customValue>
        <fullName>Esquizofrenia</fullName>
    </customValue>
    <customValue>
        <fullName>TOC</fullName>
    </customValue>
    <customValue>
        <fullName>Otros</fullName>
    </customValue>
    <customValue>
        <fullName>ACV / Ictus</fullName>
    </customValue>
    <customValue>
        <fullName>Amputación</fullName>
    </customValue>
    <customValue>
        <fullName>Caídas</fullName>
    </customValue>
    <customValue>
        <fullName>Cáncer</fullName>
    </customValue>
    <customValue>
        <fullName>Esclerosis</fullName>
    </customValue>
    <customValue>
        <fullName>Fractura</fullName>
    </customValue>
    <customValue>
        <fullName>Problemas cardiovasculares (Infarto, ICC, HTA, Arritmias, Fibrilación, Diabetes…)</fullName>
    </customValue>
    <customValue>
        <fullName>Movilidad reducida</fullName>
    </customValue>
    <customValue>
        <fullName>Paliativos</fullName>
    </customValue>
    <customValue>
        <fullName>Parkinson</fullName>
    </customValue>
    <customValue>
        <fullName>Operación / Convalecencia</fullName>
    </customValue>
    <customValue>
        <fullName>Problemas respiratorios (O2, Neutomonía, EPOC...)</fullName>
    </customValue>
    <customValue>
        <fullName>Otras</fullName>
    </customValue>
    <customValue>
        <fullName>Alteraciones de conducta</fullName>
    </customValue>
    <customValue>
        <fullName>Alzheimer</fullName>
    </customValue>
    <customValue>
        <fullName>Cuerpo Lewy</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia fronto-temporal</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia senil</fullName>
    </customValue>
    <customValue>
        <fullName>Demencia vascular</fullName>
    </customValue>
    <customValue>
        <fullName>Desorientación / Riesgo fuga</fullName>
    </customValue>
    <customValue>
        <fullName>Perdidas memoria</fullName>
    </customValue>
    <customValue>
        <fullName>ELA</fullName>
    </customValue>
    <customValue>
        <fullName>De la competencia por descontento</fullName>
    </customValue>
    <description>Valores del campo Detalle Motivo de Ingreso del Lead y Opp</description>
    <masterLabel>Detalle Motivo de Ingreso</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Genero.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Hombre</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Mujer</label>
    </customValue>
    <description>Genero del residente: hombre o mujer</description>
    <masterLabel>Género</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/MotivoIngreso.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Psicogeriatría</fullName>
    </customValue>
    <customValue>
        <fullName>Dependencia cognitiva</fullName>
    </customValue>
    <customValue>
        <fullName>Dependencia física</fullName>
    </customValue>
    <customValue>
        <fullName>Dependencia física y cognitiva</fullName>
    </customValue>
    <customValue>
        <fullName>Aspectos sociales</fullName>
    </customValue>
    <customValue>
        <fullName>Traslado residencia</fullName>
    </customValue>
    <customValue>
        <fullName>Plaza Pública</fullName>
    </customValue>
    <description>Valores de motivo de ingreso en Leads y Opps</description>
    <masterLabel>Motivo de Ingreso</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/TipoPlaza.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P</fullName>
        <label>Privada</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Pública</label>
    </customValue>
    <description>Tipo de plaza que se solicita</description>
    <masterLabel>Tipo de plaza</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestTriggerEvent.cls
/**
@description
Test Methods de la clase TriggerEvent

DATE 		AUTHOR 		DESCRIPTION
24/07/2023  MSA - LCS   Corrección de las clases test.
13/03/2023  LCS - MSA   Creación

@author Leadclic Solutions
@date 13/03/2023 
*/

@isTest 
public class TestTriggerEvent {
    private static final Id accountCentroRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('CentroResidencia').getRecordTypeId();
    private static final Id plazaResidenciaRTId = Schema.SObjectType.Plaza__c.getRecordTypeInfosByDeveloperName().get('Residencia').getRecordTypeId();
    private static final Id plazaCentroDiaRTId = Schema.SObjectType.Plaza__c.getRecordTypeInfosByDeveloperName().get('CentroDia').getRecordTypeId();
    private static final Id accountFamiliaRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('FamiliaAllegado').getRecordTypeId();
    private static final Id contactFamiliarRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('FamiliaAllegado').getRecordTypeId();
    private static final Id contactResidenteRTId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('PotencialResidente').getRecordTypeId();
    private static final Id opportunityPlazaPrivadaRTId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('PlazaPrivada').getRecordTypeId();

    @TestSetup
    static void setup(){        

        // Damos de alta un centro
        Account centro = new Account(
            Name = 'Centro de prueba',
            RecordTypeId = accountCentroRTId,
            CodigoCentroSAP__c = '2808'
        );
        insert centro;

        // Creamos una plaza para ese centro

        //Insertamos una cuenta para relacionar la oportunidad
        Account familia = new Account(
            Name = 'CuentaFamilia',
            RecordTypeId = accountFamiliaRTId
        );
        insert familia;

        Account familia2 = new Account(
            Name = 'CuentaFamilia2',
            RecordTypeId = accountFamiliaRTId
        );
        insert familia2;

        //Generamos un contacto como residente y dos familiares
        List <Contact> lCont2Insert = new List <Contact>();
        Contact residente = new Contact(
            RecordTypeId = contactResidenteRTId,
            AccountId = familia.Id,
            IdExternoSAP__c='9999',
            FirstName='ResidentePrueba',
            LastName='ApellidoPruebaResidente',
            MailingStreet='Ancha',
            MailingPostalCode='28005',
            MailingCity='Madrid',
            MobilePhone='602275300',
            Phone='917390566',
            Email='mailresidente@test.com',
            Sexo__c = '2',
            TipoDocumento__c = '01',
            NumeroDocumento__c = '02796904N'
        );
        lCont2Insert.add(residente);
        
        Contact familiar1 = new Contact(
            RecordTypeId = contactFamiliarRTId,
            AccountId = familia.Id,
            IdExternoSAP__c='8888',
            FirstName='FamiliarPrueba',
            LastName='ApellidoPruebafamiliar1Decisor',
            MailingStreet='Ancha',
            MailingPostalCode='28005',
            MailingCity='Madrid',
            MobilePhone='602275300',
            Phone='917390566',
            Email='mailfmailiar1@test.com'
        );
        lCont2Insert.add(familiar1);

        Contact familiar2 = new Contact(
            RecordTypeId = contactFamiliarRTId,
            AccountId = familia.Id,
            IdExternoSAP__c='7777',
            FirstName='FamiliarPrueba',
            LastName='ApellidoPruebaFamiliar2Influyente',
            MailingStreet='Ancha',
            MailingPostalCode='28005',
            MailingCity='Madrid',
            MobilePhone='602275300',
            Phone='917390566',
            Email='mailfamiliar2@test.com'
        );
        lCont2Insert.add(familiar2);
        
        Contact familiar3 = new Contact(
            RecordTypeId = contactFamiliarRTId,
            AccountId = familia2.Id,
            IdExternoSAP__c='3333',
            FirstName='FamiliarPrueba',
            LastName='ApellidoPruebaFamiliar3Decisor',
            MailingStreet='Ancha',
            MailingPostalCode='28003',
            MailingCity='Madrid',
            MobilePhone='603375300',
            Phone='917390533',
            Email='mailfamiliar3@test.com'
        );
        lCont2Insert.add(familiar3);

        // Insertamos los contactos
        insert lCont2Insert;

        // Insertamos una oportunidad
        Opportunity oportunidad = new Opportunity(
            AccountId = familia.Id,
            Name = 'Oportunidad de prueba',
            RecordTypeId = opportunityPlazaPrivadaRTId,
            StageName = Opportunity.StageName.getDescribe().getPicklistValues()[0].getValue(),
            CloseDate = Date.today(),
            ResidenciaIngreso__c = centro.Id,
            TipoPlaza__c = 'P',
            FechaIngresoPlanificado__c = Date.today(),
            MotivoIngreso__c = 'Psicogeriatría',
            DetalleMotivoIngreso__c = 'Autolisis'
        );
        insert oportunidad;
    }

    @isTest 
    static void testErrorOk(){

        Opportunity oportunidad = [SELECT Id from Opportunity WHERE TipoPlaza__c = 'P'];
        Contact contacto = [Select Id from Contact WHERE LastName = 'ApellidoPruebaFamiliar3Decisor'];
        event evento = new event();
        evento.WhatId = oportunidad.Id;
        evento.WhoId = contacto.Id;
        evento.type = 'Jornada';
        evento.DurationInMinutes = 30;
        evento.ActivityDateTime = datetime.now();
        test.startTest();
        try{
        insert evento;
        } catch(Exception e){
            Boolean expectedExceptionThrown =  (e.getMessage().contains('El contacto y la oportunidad deben estar relacionados.')) ? true : false; 
            System.AssertEquals(true, expectedExceptionThrown, e.getMessage()); 
        }
        test.stopTest(); 
    }

    @isTest 
    static void testErrorFalse(){

        Opportunity oportunidad = [SELECT Id from Opportunity WHERE TipoPlaza__c = 'P'];
        Contact contacto = [Select Id from Contact WHERE LastName = 'ApellidoPruebaFamiliar2Influyente'];
        event evento = new event();
        evento.WhatId = oportunidad.Id;
        evento.WhoId = contacto.Id;
        evento.type = 'Jornada';
        evento.DurationInMinutes = 30;
        evento.ActivityDateTime = datetime.now();
        test.startTest();
        insert evento;
        test.stopTest();
        List<event> eventos = [Select Id from event];
        System.assert(eventos.size()==1); 
    }
}