force-app/main/default/objects/Contact/fields/IdExternoSAP__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAP__c</fullName>
    <description>Identificador externo de SAP para los residentes</description>
    <externalId>true</externalId>
    <label>Identificador de SAP Residentes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/IdExternoSAPContactos__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAPContactos__c</fullName>
    <description>Nos indica el Id externo de SAP para los contactos</description>
    <externalId>true</externalId>
    <label>Identificador de SAP Contactos</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/NumeroDocumento__c.field-meta.xml
<CustomField>
    <fullName>NumeroDocumento__c</fullName>
    <description>Número de indentificación del residente</description>
    <label>Número del documento</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parentesco__c.field-meta.xml
<CustomField>
    <fullName>Parentesco__c</fullName>
    <description>Parentesco de la persona de contacto</description>
    <label>Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parentesco</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Sexo__c.field-meta.xml
<CustomField>
    <fullName>Sexo__c</fullName>
    <description>Genero del residente: hombre o mujer</description>
    <label>Género</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genero</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/TipoDocumento__c.field-meta.xml
<CustomField>
    <fullName>TipoDocumento__c</fullName>
    <description>Tipo de documento de identificación del residente</description>
    <label>Tipo de documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>Pasaporte</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>NIE</label>
            </value>
            <value>
                <fullName>01</fullName>
                <label>DNI</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/FamiliaAllegado.recordType-meta.xml
<RecordType>
    <fullName>FamiliaAllegado</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo familiar o allegados</description>
    <label>Familia/Allegado</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/PotencialResidente.recordType-meta.xml
<RecordType>
    <fullName>PotencialResidente</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo residente</description>
    <label>Potencial/Residente</label>
</RecordType>

force-app/main/default/objects/Mensaje_Error__mdt/Mensaje_Error__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata Type con los valores de errorCode y errorDescription para los servicios REST de Amavir.</description>
    <label>Mensaje Error</label>
    <pluralLabel>Mensajes Error</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mensaje_Error__mdt/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <description>Código de error para respuesta servicios REST</description>
    <label>Error Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mensaje_Error__mdt/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <description>Mensaje de error o respuesta para los servicios REST</description>
    <label>Error Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/RegistrosDeErrores__c.object-meta.xml
<CustomObject>
    <description>Este objeto es un registro de errores ocasionado por los Web Services donde se verá la clase donde se ha generado el error, el mensaje que hemos recibido y el código de error.</description>
    <label>Registro de Error</label>
    <nameField>
        <displayFormat>Error-{0000000}</displayFormat>
        <label>Nombre de Registros de Errores</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de Errores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegistrosDeErrores__c/fields/ClaseGeneradora__c.field-meta.xml
<CustomField>
    <fullName>ClaseGeneradora__c</fullName>
    <description>Nos indica donde se ha ocasionado el error</description>
    <label>Clase Generadora</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/fields/CodigoError__c.field-meta.xml
<CustomField>
    <fullName>CodigoError__c</fullName>
    <description>Nos indica el código donde se ha ocasionado dicho error</description>
    <label>Código de Error</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/fields/DescripcionError__c.field-meta.xml
<CustomField>
    <fullName>DescripcionError__c</fullName>
    <description>Nos dice cual es la descripción del error generado.</description>
    <label>Descripción del Error</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/fields/MensajeRecibido__c.field-meta.xml
<CustomField>
    <fullName>MensajeRecibido__c</fullName>
    <description>Nos indica que el mensaje  que hemos recibido para que se ocasione el error.</description>
    <label>Mensaje Recibido</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Genero.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>1</fullName>
        <label>Hombre</label>
    </customValue>
    <customValue>
        <fullName>2</fullName>
        <label>Mujer</label>
    </customValue>
    <description>Genero del residente: hombre o mujer</description>
    <masterLabel>Género</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Parentesco.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B</fullName>
        <label>Hermano/a</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Cuñado/a</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cónyuge</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Pareja de hecho</label>
    </customValue>
    <customValue>
        <fullName>K</fullName>
        <label>Hijo/a</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>Otro familiar</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Nieto</label>
    </customValue>
    <customValue>
        <fullName>O</fullName>
        <label>Tío/a</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>Padre/Madre</label>
    </customValue>
    <customValue>
        <fullName>Q</fullName>
        <label>Sobrino</label>
    </customValue>
    <customValue>
        <fullName>R</fullName>
        <label>Nuera/ Yerno</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Profesional</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Tutor/a</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>No aporta</label>
    </customValue>
    <customValue>
        <fullName>X</fullName>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Yerno</label>
    </customValue>
    <description>Parentesco o relacion del contacto familiar/ allegado con el residente</description>
    <masterLabel>Parentesco/ Relación</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WSModificaPacienteFamiliar.cls
/** 
@description
<pre>
Servicio web RESTful que recibe los datos del paciente o familiar de SAP, actualiza el registro encontrado en Contactos de Salesforce y
devuelve el resultado de la operación con un código y una descripción

FECHA       AUTOR   	    DESCRIPCION<br/>
09/07/2021	RF Oliveira     Creado
16/07/2021  RF Oliveira     Modificaciones buenas prácticas (Custom Metadata Type,  se mueven queries fuera de bucles)
22/07/2021  RF Oliveira     Se modifica para que acepte un solo registro en lugar de un array
06/10/2021  MMV - LCS       Ajustes de las pruebas conjuntas. Cambio en los campos obligatorios
20/02/2022  MSA - LCS       Añadido registro de errores.
17/08/2023  MSA - LCS       Añadida búsqueda por email y número de teléfono
19/09/2023  MSA - LCS       Solucionado error valores en blanco teléfono y email
</pre>
@author Leadclic Solutions
@date 09/07/2021
*/
@RestResource(urlMapping='/WSModificaPacienteFamiliar/*')
global with sharing class WSModificaPacienteFamiliar {

    /**
    @description    Método principal del servicio. Recibe la información de un paciente o familiar actualizado en SAP y lo modifica en contactos de Salesforce
    @param          payload datos entrantes   
    @return         PayloadOut con los datos de resultado de la operación
     */
    @HttpPost
    global static PayloadOut updateContact(PayloadIn payload) {
        PayloadOut payloadOut = new PayloadOut();

        String varId;
        String varTipoRegistro;
        String mensajeExito;

        try{
            // Lista de bloqueos para el insert 
            Contact Contact2Update = new Contact();

            List<Contact> contactBusqueda = new List<Contact>();

            //Buscar si ya existe un registro de contacto con el id de entrada (si viene relleno el IdFamiliarSAP usamos ese, si no usamos IdResidenteSAP) en IdExternoSAP__c
            if ( !String.isBlank(payload.IdResidenteSAP ) ){
                varId = payload.IdResidenteSAP;
                varTipoRegistro = 'PotencialResidente';
                mensajeExito = 'residente'; //para modificar el mensaje de retorno según sea residente o familiar

                contactBusqueda = [SELECT Id, AccountId, RecordTypeId, RecordType.DeveloperName, IdExternoSAP__c FROM Contact WHERE IdExternoSAP__c = : varId AND RecordType.DeveloperName= : varTipoRegistro];
            }else{
                varId = payload.IdFamiliarSAP;
                varTipoRegistro = 'FamiliaAllegado';
                mensajeExito = 'familiar';

                contactBusqueda = [SELECT Id, AccountId, RecordTypeId, RecordType.DeveloperName, IdExternoSAP__c FROM Contact WHERE  IdExternoSAPContactos__c = : varId AND RecordType.DeveloperName= : varTipoRegistro];
            }

            //Buscamos un registro "PotencialResidente" cuyo IdExternoSAP__c coincida con el IdResidenteSAP de entrada

            if((contactBusqueda.size()==0) && (Payload.DocNo != '') && (Payload.TelNumber != '')){
                contactBusqueda = [SELECT Id, AccountId, RecordTypeId, RecordType.DeveloperName, IdExternoSAP__c FROM Contact WHERE NumeroDocumento__c =: payload.DocNo AND MobilePhone =: payload.TelNumber AND RecordType.DeveloperName= : varTipoRegistro];
                if(contactBusqueda.size()>0){
                    if(varTipoRegistro == 'FamiliaAllegado'){
                        contactBusqueda[0].IdExternoSAPContactos__c = varId;
                        update contactBusqueda;
                    }

                    if(varTipoRegistro == 'PotencialResidente'){
                        contactBusqueda[0].IdExternoSAP__c = varId;
                        update contactBusqueda;
                    }
                }
            }

            // Iteramos los bloques recibidos
            //for(PayloadIn pload : payload){
            PayloadIn pload = payload;

                // Objeto para hacer update del registro
                Contact auxContact = new Contact();

                // Chequeamos los campos obligatorios
                String missingField=checkMandatoryFields(pload);
                if(String.isBlank(missingField)){

                    if(contactBusqueda.size()>0){
                        //modifica los datos del registro con los que vienen de entrada.
                        //Si no se recibe el parámetro no se realizará actualización, si se recibe vacío se actualizará a NULL
                        auxContact.Id = contactBusqueda.get(0).Id;
                        if(varTipoRegistro == 'PotencialResidente'){
                            auxContact.IdExternoSAP__c = varId;
                        }
                        if(varTipoRegistro == 'FamiliaAllegado'){
                            auxContact.IdExternoSAPContactos__c = varId;
                        }
                        auxContact.FirstName = pload.Nname;
                        auxContact.LastName = pload.Vname;
                        auxContact.MailingStreet = pload.Street + ', ' + pload.Street2 + ', ' + pload.HouseNum1;
                        auxContact.MailingPostalCode = pload.PostCode1;
                        auxContact.MailingCity = pload.City1;
                        auxContact.MobilePhone = pload.TelNumber;
                        auxContact.Phone = pload.TelNumber1;
                        auxContact.Email = pload.EMail;
                        auxContact.Parentesco__c = pload.Relsh1;
                        auxContact.Birthdate = !String.isBlank(pload.Gbdat) ? Date.valueOf(pload.Gbdat) : null;
                        auxContact.Sexo__c = pload.Gschl;
                        auxContact.NumeroDocumento__c = pload.DocNo;
                        auxContact.TipoDocumento__c = pload.DocTyp;
                        Contact2Update=auxContact;
                    } else{
                        Mensaje_Error__mdt resp = fetchResponses('ContactoNoExiste');
                        payloadOut.errorCode = resp.Error_Code__c;
                        payloadOut.errorDescription = resp.Error_Description__c;
                        CreateErrorLog(resp.Error_Code__c, resp.Error_Description__c, payload);
                    }

                } else{
                    Mensaje_Error__mdt resp = fetchResponses('FaltaCampoObligatorio');
                    payloadOut.errorCode = resp.Error_Code__c;
                    payloadOut.errorDescription = resp.Error_Description__c + missingField;
                    CreateErrorLog(resp.Error_Code__c, resp.Error_Description__c + ' '+missingField, payload);
                }

            
            // Se ejecuta el update si no hay errores previos
            if( String.isBlank(payloadOut.errorCode) ){

                update Contact2Update;
                
                //Se recupera un Custom Metadata Type u otro según si se ha modificado residente o familiar
                Mensaje_Error__mdt resp = (mensajeExito=='residente') ? fetchResponses('ResidenteModificadoOK') : fetchResponses('FamiliarModificadoOK');
                
                payloadOut.errorCode = resp.Error_Code__c;
                payloadOut.errorDescription = resp.Error_Description__c;

            }

        }catch(Exception e){
            Mensaje_Error__mdt resp = fetchResponses('err500');
            payloadOut.errorCode = resp.Error_Code__c;
            payloadOut.errorDescription = e.getMessage();
            CreateErrorLog(resp.Error_Code__c, e.getMessage(), payload);
        }

        return payloadOut;
    }

    /**
	@description	Comprueba si se han recibido los campos obligatorios
	@param 			payload datos entrantes
	@return			String missingField con el nombre del primer campo obligatorio que falta
	*/  
    private static String checkMandatoryFields (PayloadIn payload){
        String missingField='';
    
        If (String.isNotBlank(payload.IdFamiliarSAP) && String.isBlank(payload.Relsh1)){
            missingField='Relsh1';
        } else if(String.isBlank(payload.IdResidenteSAP) && String.isBlank(payload.IdFamiliarSAP)){
            missingField='IdResidenteSAP / IdFamiliarSAP';
        } else if(String.isBlank(payload.Vname)){
            missingField='Vname';
        } else if(String.isBlank(payload.Nname)){
            missingField='Nname';
        } else if(String.isBlank(payload.Gschl) && String.isNotBlank(payload.IdResidenteSAP)){
            missingField='Gschl';
        } else if(String.isBlank(payload.DocNo) && String.isNotBlank(payload.IdResidenteSAP)){
            missingField='DocNo';
        }

        return missingField;
    }

    //Wrapper Class PayloadId con la información de recibida
	global class PayloadIn {
        public String IdResidenteSAP {get;set;}
        public String IdFamiliarSAP {get;set;}
        public String Vname {get;set;}
        public String Nname {get;set;}
        public String Street {get;set;}
        public String Street2 {get;set;}
        public String HouseNum1 {get;set;}
        public String PostCode1 {get;set;}
        public String City1 {get;set;}
        public String TelNumber {get;set;}
        public String TelNumber1 {get;set;}
        public String EMail {get;set;}
        public String Relsh1 {get;set;}
        public String Gbdat {get;set;}
        public String Gschl {get;set;}
        public String DocNo {get;set;}
        public String DocTyp {get;set;}
    }

    //Wrapper Class PayloadOut para devolver los datos del resultado de la operación
	global class PayloadOut {
        public String errorCode {get;set;}
        public String errorDescription {get;set;}
	}

    /**
	@description	Método para recuperar los códigos y mensajes de respuesta
	@param 			String errReference nombre del Custom Metadata Type que se quiere recuperar
	@return			Mensaje_Error__mdt con los campos de la respuesta
	*/ 
    public static Mensaje_Error__mdt fetchResponses(String errReference){
        Mensaje_Error__mdt response = Mensaje_Error__mdt.getInstance(errReference);
        Return response;
    }

    public static void CreateErrorLog(String Code, String ErrorDescription, PayloadIn Payload){
        RegistrosDeErrores__c ErrorGenerado = new RegistrosDeErrores__c();
        
        ErrorGenerado.CodigoError__c = Code;
        ErrorGenerado.DescripcionError__c = ErrorDescription;
        ErrorGenerado.MensajeRecibido__c = JSON.serialize(Payload);
        ErrorGenerado.ClaseGeneradora__c = 'WSModificaPacienteFamiliar';

        insert ErrorGenerado;
    }
}