force-app/main/default/objects/Contact/fields/IdExternoSAPContactos__c.field-meta.xml
<CustomField>
    <fullName>IdExternoSAPContactos__c</fullName>
    <description>Nos indica el Id externo de SAP para los contactos</description>
    <externalId>true</externalId>
    <label>Identificador de SAP Contactos</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Parentesco__c.field-meta.xml
<CustomField>
    <fullName>Parentesco__c</fullName>
    <description>Parentesco de la persona de contacto</description>
    <label>Parentesco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Parentesco</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/PotencialResidente.recordType-meta.xml
<RecordType>
    <fullName>PotencialResidente</fullName>
    <active>true</active>
    <description>Tipo de registro para los contactos de tipo residente</description>
    <label>Potencial/Residente</label>
</RecordType>

force-app/main/default/objects/IntegracionSAP__mdt/IntegracionSAP__mdt.object-meta.xml
<CustomObject>
    <description>Datos necesario para la integración con SAP</description>
    <label>IntegracionSAP</label>
    <pluralLabel>IntegracionSAP</pluralLabel>
</CustomObject>

force-app/main/default/objects/IntegracionSAP__mdt/fields/EndpointFamiliar__c.field-meta.xml
<CustomField>
    <fullName>EndpointFamiliar__c</fullName>
    <description>Indica el endpoint de llamada del servicio para crear familiares</description>
    <label>Endpoint familiar</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSAP__mdt/fields/PasswordLogin__c.field-meta.xml
<CustomField>
    <fullName>PasswordLogin__c</fullName>
    <description>contraseña usada para el login en el servicio</description>
    <label>PasswordLogin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegracionSAP__mdt/fields/UsuarioLogin__c.field-meta.xml
<CustomField>
    <fullName>UsuarioLogin__c</fullName>
    <description>Usuario para hacer el login al servicio</description>
    <label>UsuarioLogin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mensaje_Error__mdt/Mensaje_Error__mdt.object-meta.xml
<CustomObject>
    <description>Custom Metadata Type con los valores de errorCode y errorDescription para los servicios REST de Amavir.</description>
    <label>Mensaje Error</label>
    <pluralLabel>Mensajes Error</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mensaje_Error__mdt/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <description>Código de error para respuesta servicios REST</description>
    <label>Error Code</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Mensaje_Error__mdt/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <description>Mensaje de error o respuesta para los servicios REST</description>
    <label>Error Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/RegistrosDeErrores__c.object-meta.xml
<CustomObject>
    <description>Este objeto es un registro de errores ocasionado por los Web Services donde se verá la clase donde se ha generado el error, el mensaje que hemos recibido y el código de error.</description>
    <label>Registro de Error</label>
    <nameField>
        <displayFormat>Error-{0000000}</displayFormat>
        <label>Nombre de Registros de Errores</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de Errores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RegistrosDeErrores__c/fields/ClaseGeneradora__c.field-meta.xml
<CustomField>
    <fullName>ClaseGeneradora__c</fullName>
    <description>Nos indica donde se ha ocasionado el error</description>
    <label>Clase Generadora</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/fields/CodigoError__c.field-meta.xml
<CustomField>
    <fullName>CodigoError__c</fullName>
    <description>Nos indica el código donde se ha ocasionado dicho error</description>
    <label>Código de Error</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/fields/DescripcionError__c.field-meta.xml
<CustomField>
    <fullName>DescripcionError__c</fullName>
    <description>Nos dice cual es la descripción del error generado.</description>
    <label>Descripción del Error</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RegistrosDeErrores__c/fields/MensajeRecibido__c.field-meta.xml
<CustomField>
    <fullName>MensajeRecibido__c</fullName>
    <description>Nos indica que el mensaje  que hemos recibido para que se ocasione el error.</description>
    <label>Mensaje Recibido</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Parentesco.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>B</fullName>
        <label>Hermano/a</label>
    </customValue>
    <customValue>
        <fullName>C</fullName>
        <label>Cuñado/a</label>
    </customValue>
    <customValue>
        <fullName>G</fullName>
        <label>Cónyuge</label>
    </customValue>
    <customValue>
        <fullName>H</fullName>
        <label>Pareja de hecho</label>
    </customValue>
    <customValue>
        <fullName>K</fullName>
        <label>Hijo/a</label>
    </customValue>
    <customValue>
        <fullName>L</fullName>
        <label>Otro familiar</label>
    </customValue>
    <customValue>
        <fullName>N</fullName>
        <label>Nieto</label>
    </customValue>
    <customValue>
        <fullName>O</fullName>
        <label>Tío/a</label>
    </customValue>
    <customValue>
        <fullName>P</fullName>
        <label>Padre/Madre</label>
    </customValue>
    <customValue>
        <fullName>Q</fullName>
        <label>Sobrino</label>
    </customValue>
    <customValue>
        <fullName>R</fullName>
        <label>Nuera/ Yerno</label>
    </customValue>
    <customValue>
        <fullName>U</fullName>
        <label>Profesional</label>
    </customValue>
    <customValue>
        <fullName>V</fullName>
        <label>Tutor/a</label>
    </customValue>
    <customValue>
        <fullName>W</fullName>
        <label>No aporta</label>
    </customValue>
    <customValue>
        <fullName>X</fullName>
        <label>Otros</label>
    </customValue>
    <customValue>
        <fullName>Y</fullName>
        <label>Yerno</label>
    </customValue>
    <description>Parentesco o relacion del contacto familiar/ allegado con el residente</description>
    <masterLabel>Parentesco/ Relación</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ConectorFamiliares.cls
/**
@description
WebService para conectar familiares

DATE 		AUTHOR 		DESCRIPTION
03/09/2024	LCS - MSA	Creation

@author Leadclic Solutions
@date 03/09/2024
*/

public class ConectorFamiliares {

    private static String RESIDENTE_RT_DEVELOPERNAME = 'PotencialResidente';

    public static String prepareDataToSend(Contact familiar, String idResidente, String centro) {
        DOM.Document docReq = new DOM.Document();
            
        String soapNS = 'http://schemas.xmlsoap.org/soap/envelope/';
        String urn = 'urn:sap-com:document:sap:rfc:functions';
            
        dom.XmlNode envelope = docReq.createRootElement('Envelope', soapNS, 'soapenv');
        envelope.setNamespace('urn', urn);
            
        dom.XmlNode header = envelope.addChildElement('Header', soapNS, 'soapenv');
        dom.XmlNode body = envelope.addChildElement('Body', soapNS, 'soapenv');
        dom.XmlNode zish = body.addChildElement('ZISH_CREAR_FAMILIAR_SF', urn, 'urn');
        dom.XmlNode iDatos = zish.addChildElement('I_DATOS', null, null);

        dom.XmlNode EINRI = iDatos.addChildElement('EINRI', null, null);
        dom.XmlNode PATNR = iDatos.addChildElement('PATNR', null, null);
        dom.XmlNode LNAME1 = iDatos.addChildElement('LNAME1', null, null);
        dom.XmlNode FNAME1 = iDatos.addChildElement('FNAME1', null, null);
        dom.XmlNode GSCHL = iDatos.addChildElement('GSCHL', null, null);
        dom.XmlNode RELSH = iDatos.addChildElement('RELSH', null, null);
        dom.XmlNode STREET1 = iDatos.addChildElement('STREET1', null, null);
        dom.XmlNode STREET2 = iDatos.addChildElement('STREET2', null, null);
        dom.XmlNode HOUSE_NUM = iDatos.addChildElement('HOUSE_NUM', null, null);
        dom.XmlNode POST_CODE = iDatos.addChildElement('POST_CODE', null, null);
        dom.XmlNode CITY = iDatos.addChildElement('CITY', null, null);
        dom.XmlNode TEL_NUMBER = iDatos.addChildElement('TEL_NUMBER', null, null);
        dom.XmlNode E_MAIL = iDatos.addChildElement('E_MAIL', null, null);
        
        //Obligatorios
        EINRI.addTextNode(centro);
        PATNR.addTextNode(idResidente);
        LNAME1.addTextNode(familiar.LastName);
        FNAME1.addTextNode(familiar.FirstName);
        GSCHL.addTextNode(familiar.Salutation == 'D.'? 'H' : 'M');
        RELSH.addTextNode(familiar.RecordType.DeveloperName == RESIDENTE_RT_DEVELOPERNAME? 'X' : familiar.Parentesco__c);

        //No obligatorios
        STREET1.addTextNode(familiar.MailingStreet != null ? familiar.MailingStreet.left(60) : '');
        STREET2.addTextNode(familiar.MailingStreet != null ? familiar.MailingStreet.right(familiar.MailingStreet.length()-60).left(60) : '');
        HOUSE_NUM.addTextNode('');
        POST_CODE.addTextNode(familiar.MailingPostalCode != null? familiar.MailingPostalCode : '');
        CITY.addTextNode(familiar.MailingCity != null? familiar.MailingCity : '');
        TEL_NUMBER.addTextNode(familiar.MobilePhone != null? familiar.MobilePhone : '');
        E_MAIL.addTextNode(familiar.Email != null? familiar.Email : '');

        return docReq.toXmlString().replace('<?xml version="1.0" encoding="UTF-8"?>','');
    }

    @future (callout=true)
    public static void sendContact(String body, Id idFamiliar) {   
            
            HttpResponse response = makeCallOut(body);
            // Si da un error 500 no leemos la respuesta, directamente almacenamos un error en la oportunidad
            ResponseData rData = new ResponseData();
            if(response.getStatusCode() == 200){
                // Deserializamos la respuesta para sacar la información
                rData = deserializeResponse(response);

                Contact familiar = [SELECT Id, IdExternoSAPContactos__c FROM Contact WHERE Id = :idFamiliar];
                familiar.IdExternoSAPContactos__c = rData.idFamiliar;
                update familiar;
            }else{
                rData.lType = new List<String>{fetchResponses('err500').Error_Code__c};
                rData.lMessage = new List<String>{fetchResponses('err500').Error_Description__c};
                CreateErrorLog(fetchResponses('err500').Error_Code__c, fetchResponses('err500').Error_Description__c, body);
            }
    }

    /* 
    @description Método que se realiza el callout al servicio externo y actualiza los registros en función del resultado
    @param opportunityId Id de la oportunidad a enviar
    @return void no se realiza devolución
    */

    public static HttpResponse makeCallOut(String body) {

        // Recuperamos la condiguración con los datos de conexión
        IntegracionSAP__mdt config = [SELECT isSandbox FROM Organization].get(0).isSandbox ? IntegracionSAP__mdt.getInstance('Desarrollo') : IntegracionSAP__mdt.getInstance('Produccion');

        // Montamos la llamada con la información obtenida
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        System.debug('XXXx '+config.EndpointFamiliar__c);
        request.setEndpoint(config.EndpointFamiliar__c);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'text/xml');
        // Codificamoas las credenciales en base64
        String sBase64 = EncodingUtil.base64Encode(Blob.valueOf(config.UsuarioLogin__c + ':' + config.PasswordLogin__c));
        request.setHeader('Authorization', 'Basic ' + sBase64);
        request.setTimeout(120000);
        //request.setBody('<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="urn:sap-com:document:sap:rfc:functions">		   <soapenv:Body>			  <urn:ZISH_CREAR_ADMISION_SF>				 <I_DATOS>					<EINRI>0201</EINRI>					<VNAME>asd</VNAME>					<NNAME>qwerty</NNAME>					<GSCHL>M</GSCHL>					<DOC_NO>12345678I</DOC_NO>					<STREET>avenida de europa</STREET>					<HOUSE_NUM1>10</HOUSE_NUM1>					<POST_CODE1>28046</POST_CODE1>					<CITY1>Madrid</CITY1>					<BWART>AD</BWART> <!-- AD (centro dia) o AI (residencia) -->					<BEKAT>CRM</BEKAT> <!-- CRM o CDCRM -->					<ORGPF>0201MD0</ORGPF> <!-- Consultar excel de unidades organizativas -->					<BWIDT>2021-08-01</BWIDT> <!-- formato YYYY-MM-DD -->					<FATYP>I</FATYP> <!-- D (centro dia) o I (residencia)-->					<PRIVADO></PRIVADO>				 </I_DATOS>			  </urn:ZISH_CREAR_ADMISION_SF>		   </soapenv:Body>		</soapenv:Envelope>');
        request.setBody(body);
        System.debug('@@ Enviado: ' + request.getBody());
        
        
        HttpResponse response = http.send(request);
        System.debug('@@ Respuesta: ' + response.getBody());
        

        return response;
    }

    public static ResponseData deserializeResponse(HttpResponse response) {

        // Variables que almacenan los datos de vuelta
        String idBPResidente, idFamiliar;
        List <String> lMessage = new List <String>();
        List <String> lType = new List <String>();        

        Dom.Document doc = response.getBodyDocument();
        // Obtenemos y buscamos en el xml la información recibida
        Dom.XMLNode root = doc.getRootElement();
        for(Dom.XMLNode child : root.getChildElements()) {
            //System.debug(child.getName());
            if( child.getName() == 'Body'){
                for(Dom.XMLNode bodyChild : child.getChildElements()) {
                    //System.debug(bodyChild.getName());
                    if( bodyChild.getName() == 'ZISH_CREAR_FAMILIAR_SFResponse'){
                        for(Dom.XMLNode zishChild : bodyChild.getChildElements()) {
                            //System.debug(zishChild.getName());

                            // Almacenamos la información recibida en variables
                            idBPResidente = zishChild.getName() == 'E_PARTNER1' ? zishChild.getText() : idBPResidente;
                            idFamiliar = zishChild.getName() == 'E_PARTNER2' ? zishChild.getText() : idFamiliar;

                            // Buscamos y almacenamos los tipos y los mensaje de error
                            if( zishChild.getName() == 'E_RETURN'){
                                for(Dom.XMLNode returnChild : zishChild.getChildElements()) {
                                    for(Dom.XMLNode itemChild : returnChild.getChildElements()) {

                                        if( itemChild.getName() == 'TYPE' ){
                                            lType.add(itemChild.getText());
                                        }
                                        if( itemChild.getName() == 'MESSAGE' ){
                                            lMessage.add(itemChild.getText());
                                        }                                        
                                        //System.debug(itemChild.getName());
                                    }
                                }
                            }        
                        }
                    }
                }
            }            
        }

        // Devolvemos los datos recibidos
        ResponseData rData = new ResponseData();
        rData.idBPResidente = idBPResidente;
        rData.idFamiliar = idFamiliar;
        rData.lMessage = lMessage;
        rData.lType = lType;

        return rData;
    }

    private static Mensaje_Error__mdt fetchResponses(String errReference){
        Mensaje_Error__mdt response = Mensaje_Error__mdt.getInstance(errReference);
        Return response;
    }

    public static void CreateErrorLog(String code, String errorDescription, String body){
        RegistrosDeErrores__c ErrorGenerado = new RegistrosDeErrores__c();
        
        ErrorGenerado.CodigoError__c = 'SAP';
        ErrorGenerado.DescripcionError__c = code + ' ' + errorDescription;
        ErrorGenerado.MensajeRecibido__c = body;
        ErrorGenerado.ClaseGeneradora__c = 'ConectorFamiliares';

        insert ErrorGenerado;
    }

    private class ResponseData {
        String idBPResidente {get;set;} //No es el ID del residente
        String idFamiliar {get;set;}
        List<String> lMessage {get;set;}
        List<String> lType {get;set;}
    }
}